//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.07 at 06:17:52 PM CEST 
//


package org.w3._1999.xhtml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3._1998.math.mathml.Math;
import org.w3._1999.xsl.format.TableBorderStyleType;
import uk.co.tso.assets.namespace.error.ErrorType;
import uk.gov.legislation.namespaces.legislation.Abbreviation;
import uk.gov.legislation.namespaces.legislation.Acronym;
import uk.gov.legislation.namespaces.legislation.ChangeType;
import uk.gov.legislation.namespaces.legislation.Character;
import uk.gov.legislation.namespaces.legislation.Citation;
import uk.gov.legislation.namespaces.legislation.CitationListRef;
import uk.gov.legislation.namespaces.legislation.CitationSubRef;
import uk.gov.legislation.namespaces.legislation.CommentaryRef;
import uk.gov.legislation.namespaces.legislation.DecoratedGroup;
import uk.gov.legislation.namespaces.legislation.Definition;
import uk.gov.legislation.namespaces.legislation.Emphasis;
import uk.gov.legislation.namespaces.legislation.ExternalLink;
import uk.gov.legislation.namespaces.legislation.Figure;
import uk.gov.legislation.namespaces.legislation.FootnoteRef;
import uk.gov.legislation.namespaces.legislation.Form;
import uk.gov.legislation.namespaces.legislation.Formula;
import uk.gov.legislation.namespaces.legislation.Image;
import uk.gov.legislation.namespaces.legislation.InlineAmendment;
import uk.gov.legislation.namespaces.legislation.InlineExtract;
import uk.gov.legislation.namespaces.legislation.InlineStructure;
import uk.gov.legislation.namespaces.legislation.InternalLink;
import uk.gov.legislation.namespaces.legislation.KeyList;
import uk.gov.legislation.namespaces.legislation.MarginNoteRef;
import uk.gov.legislation.namespaces.legislation.OrderedList;
import uk.gov.legislation.namespaces.legislation.P;
import uk.gov.legislation.namespaces.legislation.P1;
import uk.gov.legislation.namespaces.legislation.P1Group;
import uk.gov.legislation.namespaces.legislation.P2;
import uk.gov.legislation.namespaces.legislation.P2Group;
import uk.gov.legislation.namespaces.legislation.P3;
import uk.gov.legislation.namespaces.legislation.P3Group;
import uk.gov.legislation.namespaces.legislation.P4;
import uk.gov.legislation.namespaces.legislation.P5;
import uk.gov.legislation.namespaces.legislation.P6;
import uk.gov.legislation.namespaces.legislation.P7;
import uk.gov.legislation.namespaces.legislation.Para;
import uk.gov.legislation.namespaces.legislation.Proviso;
import uk.gov.legislation.namespaces.legislation.Repeal;
import uk.gov.legislation.namespaces.legislation.SmallCaps;
import uk.gov.legislation.namespaces.legislation.Strong;
import uk.gov.legislation.namespaces.legislation.Tabular;
import uk.gov.legislation.namespaces.legislation.Term;
import uk.gov.legislation.namespaces.legislation.UnorderedList;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://www.legislation.gov.uk/namespaces/legislation}TableCell" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;attGroup ref="{http://www.w3.org/1999/XSL/Format}TableBorderAttributes"/>
 *       &lt;attGroup ref="{http://www.w3.org/1999/xhtml}TableID"/>
 *       &lt;attGroup ref="{http://www.w3.org/1999/xhtml}TableCellAttributes"/>
 *       &lt;attGroup ref="{http://www.w3.org/1999/XSL/Format}TableBorderTopAttributes"/>
 *       &lt;attGroup ref="{http://www.w3.org/1999/XSL/Format}TableBackgroundColorAttributes"/>
 *       &lt;attGroup ref="{http://www.w3.org/1999/xhtml}TableXMLattributes"/>
 *       &lt;attGroup ref="{http://www.w3.org/1999/XSL/Format}TableBorderLeftAttributes"/>
 *       &lt;attribute name="headers" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "td")
public class Td {

    @XmlElementRefs({
        @XmlElementRef(name = "ExternalLink", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = ExternalLink.class, required = false),
        @XmlElementRef(name = "Addition", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "table", namespace = "http://www.w3.org/1999/xhtml", type = Table.class, required = false),
        @XmlElementRef(name = "math", namespace = "http://www.w3.org/1998/Math/MathML", type = Math.class, required = false),
        @XmlElementRef(name = "MarginNoteRef", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = MarginNoteRef.class, required = false),
        @XmlElementRef(name = "Acronym", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Acronym.class, required = false),
        @XmlElementRef(name = "Form", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Form.class, required = false),
        @XmlElementRef(name = "P3", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = P3 .class, required = false),
        @XmlElementRef(name = "P5", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = P5 .class, required = false),
        @XmlElementRef(name = "CitationListRef", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = CitationListRef.class, required = false),
        @XmlElementRef(name = "Abbreviation", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Abbreviation.class, required = false),
        @XmlElementRef(name = "Strong", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Strong.class, required = false),
        @XmlElementRef(name = "Para", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Para.class, required = false),
        @XmlElementRef(name = "Emphasis", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Emphasis.class, required = false),
        @XmlElementRef(name = "Term", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Term.class, required = false),
        @XmlElementRef(name = "Image", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Image.class, required = false),
        @XmlElementRef(name = "InlineExtract", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = InlineExtract.class, required = false),
        @XmlElementRef(name = "KeyList", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = KeyList.class, required = false),
        @XmlElementRef(name = "Figure", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Figure.class, required = false),
        @XmlElementRef(name = "P3group", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = P3Group.class, required = false),
        @XmlElementRef(name = "Error", namespace = "http://www.tso.co.uk/assets/namespace/error", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Span", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Character", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Character.class, required = false),
        @XmlElementRef(name = "Citation", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Citation.class, required = false),
        @XmlElementRef(name = "Underline", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Substitution", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "OrderedList", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = OrderedList.class, required = false),
        @XmlElementRef(name = "Proviso", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Proviso.class, required = false),
        @XmlElementRef(name = "DecoratedGroup", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = DecoratedGroup.class, required = false),
        @XmlElementRef(name = "InlineAmendment", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = InlineAmendment.class, required = false),
        @XmlElementRef(name = "CommentaryRef", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = CommentaryRef.class, required = false),
        @XmlElementRef(name = "P6", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = P6 .class, required = false),
        @XmlElementRef(name = "P4", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = P4 .class, required = false),
        @XmlElementRef(name = "InternalLink", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = InternalLink.class, required = false),
        @XmlElementRef(name = "P2", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = P2 .class, required = false),
        @XmlElementRef(name = "UnorderedList", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = UnorderedList.class, required = false),
        @XmlElementRef(name = "P2group", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = P2Group.class, required = false),
        @XmlElementRef(name = "Warning", namespace = "http://www.tso.co.uk/assets/namespace/error", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Inferior", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "P", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = P.class, required = false),
        @XmlElementRef(name = "P1", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = P1 .class, required = false),
        @XmlElementRef(name = "Tabular", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Tabular.class, required = false),
        @XmlElementRef(name = "Formula", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Formula.class, required = false),
        @XmlElementRef(name = "P7", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = P7 .class, required = false),
        @XmlElementRef(name = "CitationSubRef", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = CitationSubRef.class, required = false),
        @XmlElementRef(name = "SmallCaps", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = SmallCaps.class, required = false),
        @XmlElementRef(name = "Superior", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "FootnoteRef", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = FootnoteRef.class, required = false),
        @XmlElementRef(name = "Repeal", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Repeal.class, required = false),
        @XmlElementRef(name = "Definition", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Definition.class, required = false),
        @XmlElementRef(name = "P1group", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = P1Group.class, required = false)
    })
    @XmlMixed
    protected List<Object> content;
    @XmlAttribute(name = "headers")
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> headers;
    @XmlAttribute(name = "border-right-style", namespace = "http://www.w3.org/1999/XSL/Format")
    protected TableBorderStyleType borderRightStyle;
    @XmlAttribute(name = "border-bottom-style", namespace = "http://www.w3.org/1999/XSL/Format")
    protected TableBorderStyleType borderBottomStyle;
    @XmlAttribute(name = "border-right-color", namespace = "http://www.w3.org/1999/XSL/Format")
    protected String borderRightColor;
    @XmlAttribute(name = "border-bottom-color", namespace = "http://www.w3.org/1999/XSL/Format")
    protected String borderBottomColor;
    @XmlAttribute(name = "border-right-width", namespace = "http://www.w3.org/1999/XSL/Format")
    protected String borderRightWidth;
    @XmlAttribute(name = "border-bottom-width", namespace = "http://www.w3.org/1999/XSL/Format")
    protected String borderBottomWidth;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "colspan")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger colspan;
    @XmlAttribute(name = "rowspan")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger rowspan;
    @XmlAttribute(name = "height")
    protected String height;
    @XmlAttribute(name = "width")
    protected String width;
    @XmlAttribute(name = "valign")
    protected String valign;
    @XmlAttribute(name = "align")
    protected String align;
    @XmlAttribute(name = "reference-orientation", namespace = "http://www.w3.org/1999/XSL/Format")
    protected String referenceOrientation;
    @XmlAttribute(name = "border-top-style", namespace = "http://www.w3.org/1999/XSL/Format")
    protected TableBorderStyleType borderTopStyle;
    @XmlAttribute(name = "border-top-color", namespace = "http://www.w3.org/1999/XSL/Format")
    protected String borderTopColor;
    @XmlAttribute(name = "border-top-width", namespace = "http://www.w3.org/1999/XSL/Format")
    protected String borderTopWidth;
    @XmlAttribute(name = "background-color", namespace = "http://www.w3.org/1999/XSL/Format")
    protected String backgroundColor;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String lang;
    @XmlAttribute(name = "space", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String space;
    @XmlAttribute(name = "base", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlSchemaType(name = "anyURI")
    protected String base;
    @XmlAttribute(name = "border-left-style", namespace = "http://www.w3.org/1999/XSL/Format")
    protected TableBorderStyleType borderLeftStyle;
    @XmlAttribute(name = "border-left-color", namespace = "http://www.w3.org/1999/XSL/Format")
    protected String borderLeftColor;
    @XmlAttribute(name = "border-left-width", namespace = "http://www.w3.org/1999/XSL/Format")
    protected String borderLeftWidth;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExternalLink }
     * {@link JAXBElement }{@code <}{@link ChangeType }{@code >}
     * {@link Table }
     * {@link Math }
     * {@link MarginNoteRef }
     * {@link Acronym }
     * {@link Form }
     * {@link P3 }
     * {@link P5 }
     * {@link CitationListRef }
     * {@link Abbreviation }
     * {@link Strong }
     * {@link Para }
     * {@link Emphasis }
     * {@link Term }
     * {@link Image }
     * {@link InlineExtract }
     * {@link KeyList }
     * {@link Figure }
     * {@link P3Group }
     * {@link JAXBElement }{@code <}{@link ErrorType }{@code >}
     * {@link JAXBElement }{@code <}{@link InlineStructure }{@code >}
     * {@link Character }
     * {@link Citation }
     * {@link JAXBElement }{@code <}{@link InlineStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link ChangeType }{@code >}
     * {@link OrderedList }
     * {@link String }
     * {@link Proviso }
     * {@link DecoratedGroup }
     * {@link InlineAmendment }
     * {@link CommentaryRef }
     * {@link P6 }
     * {@link P4 }
     * {@link InternalLink }
     * {@link P2 }
     * {@link UnorderedList }
     * {@link P2Group }
     * {@link JAXBElement }{@code <}{@link ErrorType }{@code >}
     * {@link JAXBElement }{@code <}{@link InlineStructure }{@code >}
     * {@link P }
     * {@link P1 }
     * {@link Tabular }
     * {@link Formula }
     * {@link P7 }
     * {@link CitationSubRef }
     * {@link SmallCaps }
     * {@link JAXBElement }{@code <}{@link InlineStructure }{@code >}
     * {@link FootnoteRef }
     * {@link Repeal }
     * {@link P1Group }
     * {@link Definition }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the headers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the headers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHeaders().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getHeaders() {
        if (headers == null) {
            headers = new ArrayList<Object>();
        }
        return this.headers;
    }

    /**
     * Gets the value of the borderRightStyle property.
     * 
     * @return
     *     possible object is
     *     {@link TableBorderStyleType }
     *     
     */
    public TableBorderStyleType getBorderRightStyle() {
        if (borderRightStyle == null) {
            return TableBorderStyleType.INHERIT;
        } else {
            return borderRightStyle;
        }
    }

    /**
     * Sets the value of the borderRightStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableBorderStyleType }
     *     
     */
    public void setBorderRightStyle(TableBorderStyleType value) {
        this.borderRightStyle = value;
    }

    /**
     * Gets the value of the borderBottomStyle property.
     * 
     * @return
     *     possible object is
     *     {@link TableBorderStyleType }
     *     
     */
    public TableBorderStyleType getBorderBottomStyle() {
        if (borderBottomStyle == null) {
            return TableBorderStyleType.INHERIT;
        } else {
            return borderBottomStyle;
        }
    }

    /**
     * Sets the value of the borderBottomStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableBorderStyleType }
     *     
     */
    public void setBorderBottomStyle(TableBorderStyleType value) {
        this.borderBottomStyle = value;
    }

    /**
     * Gets the value of the borderRightColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderRightColor() {
        if (borderRightColor == null) {
            return "inherit";
        } else {
            return borderRightColor;
        }
    }

    /**
     * Sets the value of the borderRightColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderRightColor(String value) {
        this.borderRightColor = value;
    }

    /**
     * Gets the value of the borderBottomColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderBottomColor() {
        if (borderBottomColor == null) {
            return "inherit";
        } else {
            return borderBottomColor;
        }
    }

    /**
     * Sets the value of the borderBottomColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderBottomColor(String value) {
        this.borderBottomColor = value;
    }

    /**
     * Gets the value of the borderRightWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderRightWidth() {
        if (borderRightWidth == null) {
            return "inherit";
        } else {
            return borderRightWidth;
        }
    }

    /**
     * Sets the value of the borderRightWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderRightWidth(String value) {
        this.borderRightWidth = value;
    }

    /**
     * Gets the value of the borderBottomWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderBottomWidth() {
        if (borderBottomWidth == null) {
            return "inherit";
        } else {
            return borderBottomWidth;
        }
    }

    /**
     * Sets the value of the borderBottomWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderBottomWidth(String value) {
        this.borderBottomWidth = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the colspan property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getColspan() {
        if (colspan == null) {
            return new BigInteger("1");
        } else {
            return colspan;
        }
    }

    /**
     * Sets the value of the colspan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setColspan(BigInteger value) {
        this.colspan = value;
    }

    /**
     * Gets the value of the rowspan property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRowspan() {
        if (rowspan == null) {
            return new BigInteger("1");
        } else {
            return rowspan;
        }
    }

    /**
     * Sets the value of the rowspan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRowspan(BigInteger value) {
        this.rowspan = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeight(String value) {
        this.height = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidth(String value) {
        this.width = value;
    }

    /**
     * Gets the value of the valign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValign() {
        return valign;
    }

    /**
     * Sets the value of the valign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValign(String value) {
        this.valign = value;
    }

    /**
     * Gets the value of the align property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlign() {
        if (align == null) {
            return "inherit";
        } else {
            return align;
        }
    }

    /**
     * Sets the value of the align property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlign(String value) {
        this.align = value;
    }

    /**
     * Gets the value of the referenceOrientation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceOrientation() {
        return referenceOrientation;
    }

    /**
     * Sets the value of the referenceOrientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceOrientation(String value) {
        this.referenceOrientation = value;
    }

    /**
     * Gets the value of the borderTopStyle property.
     * 
     * @return
     *     possible object is
     *     {@link TableBorderStyleType }
     *     
     */
    public TableBorderStyleType getBorderTopStyle() {
        if (borderTopStyle == null) {
            return TableBorderStyleType.INHERIT;
        } else {
            return borderTopStyle;
        }
    }

    /**
     * Sets the value of the borderTopStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableBorderStyleType }
     *     
     */
    public void setBorderTopStyle(TableBorderStyleType value) {
        this.borderTopStyle = value;
    }

    /**
     * Gets the value of the borderTopColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderTopColor() {
        if (borderTopColor == null) {
            return "inherit";
        } else {
            return borderTopColor;
        }
    }

    /**
     * Sets the value of the borderTopColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderTopColor(String value) {
        this.borderTopColor = value;
    }

    /**
     * Gets the value of the borderTopWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderTopWidth() {
        if (borderTopWidth == null) {
            return "inherit";
        } else {
            return borderTopWidth;
        }
    }

    /**
     * Sets the value of the borderTopWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderTopWidth(String value) {
        this.borderTopWidth = value;
    }

    /**
     * Gets the value of the backgroundColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundColor() {
        return backgroundColor;
    }

    /**
     * Sets the value of the backgroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundColor(String value) {
        this.backgroundColor = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpace() {
        return space;
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpace(String value) {
        this.space = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

    /**
     * Gets the value of the borderLeftStyle property.
     * 
     * @return
     *     possible object is
     *     {@link TableBorderStyleType }
     *     
     */
    public TableBorderStyleType getBorderLeftStyle() {
        if (borderLeftStyle == null) {
            return TableBorderStyleType.INHERIT;
        } else {
            return borderLeftStyle;
        }
    }

    /**
     * Sets the value of the borderLeftStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableBorderStyleType }
     *     
     */
    public void setBorderLeftStyle(TableBorderStyleType value) {
        this.borderLeftStyle = value;
    }

    /**
     * Gets the value of the borderLeftColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderLeftColor() {
        if (borderLeftColor == null) {
            return "inherit";
        } else {
            return borderLeftColor;
        }
    }

    /**
     * Sets the value of the borderLeftColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderLeftColor(String value) {
        this.borderLeftColor = value;
    }

    /**
     * Gets the value of the borderLeftWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderLeftWidth() {
        if (borderLeftWidth == null) {
            return "inherit";
        } else {
            return borderLeftWidth;
        }
    }

    /**
     * Sets the value of the borderLeftWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderLeftWidth(String value) {
        this.borderLeftWidth = value;
    }

}
