//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.07 at 06:17:52 PM CEST 
//


package org.w3._1999.xhtml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3._1999.xsl.format.TableBorderStyleType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://www.w3.org/1999/xhtml}td"/>
 *         &lt;element ref="{http://www.w3.org/1999/xhtml}th"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{http://www.w3.org/1999/XSL/Format}TableBackgroundColorAttributes"/>
 *       &lt;attGroup ref="{http://www.w3.org/1999/XSL/Format}TableBorderTopAttributes"/>
 *       &lt;attGroup ref="{http://www.w3.org/1999/XSL/Format}TableBorderLeftAttributes"/>
 *       &lt;attGroup ref="{http://www.w3.org/1999/xhtml}TableXMLattributes"/>
 *       &lt;attGroup ref="{http://www.w3.org/1999/XSL/Format}TableBorderAttributes"/>
 *       &lt;attGroup ref="{http://www.w3.org/1999/xhtml}TableID"/>
 *       &lt;attribute name="height" type="{http://www.w3.org/1999/xhtml}TableSimpleLengthType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tdsAndThs"
})
@XmlRootElement(name = "tr")
public class Tr {

    @XmlElements({
        @XmlElement(name = "td", type = Td.class),
        @XmlElement(name = "th", type = Th.class)
    })
    protected List<Object> tdsAndThs;
    @XmlAttribute(name = "height")
    protected String height;
    @XmlAttribute(name = "background-color", namespace = "http://www.w3.org/1999/XSL/Format")
    protected String backgroundColor;
    @XmlAttribute(name = "border-top-style", namespace = "http://www.w3.org/1999/XSL/Format")
    protected TableBorderStyleType borderTopStyle;
    @XmlAttribute(name = "border-top-color", namespace = "http://www.w3.org/1999/XSL/Format")
    protected String borderTopColor;
    @XmlAttribute(name = "border-top-width", namespace = "http://www.w3.org/1999/XSL/Format")
    protected String borderTopWidth;
    @XmlAttribute(name = "border-left-style", namespace = "http://www.w3.org/1999/XSL/Format")
    protected TableBorderStyleType borderLeftStyle;
    @XmlAttribute(name = "border-left-color", namespace = "http://www.w3.org/1999/XSL/Format")
    protected String borderLeftColor;
    @XmlAttribute(name = "border-left-width", namespace = "http://www.w3.org/1999/XSL/Format")
    protected String borderLeftWidth;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String lang;
    @XmlAttribute(name = "space", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String space;
    @XmlAttribute(name = "base", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlSchemaType(name = "anyURI")
    protected String base;
    @XmlAttribute(name = "border-right-style", namespace = "http://www.w3.org/1999/XSL/Format")
    protected TableBorderStyleType borderRightStyle;
    @XmlAttribute(name = "border-bottom-style", namespace = "http://www.w3.org/1999/XSL/Format")
    protected TableBorderStyleType borderBottomStyle;
    @XmlAttribute(name = "border-right-color", namespace = "http://www.w3.org/1999/XSL/Format")
    protected String borderRightColor;
    @XmlAttribute(name = "border-bottom-color", namespace = "http://www.w3.org/1999/XSL/Format")
    protected String borderBottomColor;
    @XmlAttribute(name = "border-right-width", namespace = "http://www.w3.org/1999/XSL/Format")
    protected String borderRightWidth;
    @XmlAttribute(name = "border-bottom-width", namespace = "http://www.w3.org/1999/XSL/Format")
    protected String borderBottomWidth;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;

    /**
     * Gets the value of the tdsAndThs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tdsAndThs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTdsAndThs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Td }
     * {@link Th }
     * 
     * 
     */
    public List<Object> getTdsAndThs() {
        if (tdsAndThs == null) {
            tdsAndThs = new ArrayList<Object>();
        }
        return this.tdsAndThs;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeight(String value) {
        this.height = value;
    }

    /**
     * Gets the value of the backgroundColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundColor() {
        return backgroundColor;
    }

    /**
     * Sets the value of the backgroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundColor(String value) {
        this.backgroundColor = value;
    }

    /**
     * Gets the value of the borderTopStyle property.
     * 
     * @return
     *     possible object is
     *     {@link TableBorderStyleType }
     *     
     */
    public TableBorderStyleType getBorderTopStyle() {
        if (borderTopStyle == null) {
            return TableBorderStyleType.INHERIT;
        } else {
            return borderTopStyle;
        }
    }

    /**
     * Sets the value of the borderTopStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableBorderStyleType }
     *     
     */
    public void setBorderTopStyle(TableBorderStyleType value) {
        this.borderTopStyle = value;
    }

    /**
     * Gets the value of the borderTopColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderTopColor() {
        if (borderTopColor == null) {
            return "inherit";
        } else {
            return borderTopColor;
        }
    }

    /**
     * Sets the value of the borderTopColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderTopColor(String value) {
        this.borderTopColor = value;
    }

    /**
     * Gets the value of the borderTopWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderTopWidth() {
        if (borderTopWidth == null) {
            return "inherit";
        } else {
            return borderTopWidth;
        }
    }

    /**
     * Sets the value of the borderTopWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderTopWidth(String value) {
        this.borderTopWidth = value;
    }

    /**
     * Gets the value of the borderLeftStyle property.
     * 
     * @return
     *     possible object is
     *     {@link TableBorderStyleType }
     *     
     */
    public TableBorderStyleType getBorderLeftStyle() {
        if (borderLeftStyle == null) {
            return TableBorderStyleType.INHERIT;
        } else {
            return borderLeftStyle;
        }
    }

    /**
     * Sets the value of the borderLeftStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableBorderStyleType }
     *     
     */
    public void setBorderLeftStyle(TableBorderStyleType value) {
        this.borderLeftStyle = value;
    }

    /**
     * Gets the value of the borderLeftColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderLeftColor() {
        if (borderLeftColor == null) {
            return "inherit";
        } else {
            return borderLeftColor;
        }
    }

    /**
     * Sets the value of the borderLeftColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderLeftColor(String value) {
        this.borderLeftColor = value;
    }

    /**
     * Gets the value of the borderLeftWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderLeftWidth() {
        if (borderLeftWidth == null) {
            return "inherit";
        } else {
            return borderLeftWidth;
        }
    }

    /**
     * Sets the value of the borderLeftWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderLeftWidth(String value) {
        this.borderLeftWidth = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpace() {
        return space;
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpace(String value) {
        this.space = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

    /**
     * Gets the value of the borderRightStyle property.
     * 
     * @return
     *     possible object is
     *     {@link TableBorderStyleType }
     *     
     */
    public TableBorderStyleType getBorderRightStyle() {
        if (borderRightStyle == null) {
            return TableBorderStyleType.INHERIT;
        } else {
            return borderRightStyle;
        }
    }

    /**
     * Sets the value of the borderRightStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableBorderStyleType }
     *     
     */
    public void setBorderRightStyle(TableBorderStyleType value) {
        this.borderRightStyle = value;
    }

    /**
     * Gets the value of the borderBottomStyle property.
     * 
     * @return
     *     possible object is
     *     {@link TableBorderStyleType }
     *     
     */
    public TableBorderStyleType getBorderBottomStyle() {
        if (borderBottomStyle == null) {
            return TableBorderStyleType.INHERIT;
        } else {
            return borderBottomStyle;
        }
    }

    /**
     * Sets the value of the borderBottomStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableBorderStyleType }
     *     
     */
    public void setBorderBottomStyle(TableBorderStyleType value) {
        this.borderBottomStyle = value;
    }

    /**
     * Gets the value of the borderRightColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderRightColor() {
        if (borderRightColor == null) {
            return "inherit";
        } else {
            return borderRightColor;
        }
    }

    /**
     * Sets the value of the borderRightColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderRightColor(String value) {
        this.borderRightColor = value;
    }

    /**
     * Gets the value of the borderBottomColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderBottomColor() {
        if (borderBottomColor == null) {
            return "inherit";
        } else {
            return borderBottomColor;
        }
    }

    /**
     * Sets the value of the borderBottomColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderBottomColor(String value) {
        this.borderBottomColor = value;
    }

    /**
     * Gets the value of the borderRightWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderRightWidth() {
        if (borderRightWidth == null) {
            return "inherit";
        } else {
            return borderRightWidth;
        }
    }

    /**
     * Sets the value of the borderRightWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderRightWidth(String value) {
        this.borderRightWidth = value;
    }

    /**
     * Gets the value of the borderBottomWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderBottomWidth() {
        if (borderBottomWidth == null) {
            return "inherit";
        } else {
            return borderBottomWidth;
        }
    }

    /**
     * Sets the value of the borderBottomWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderBottomWidth(String value) {
        this.borderBottomWidth = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
