//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.07 at 06:17:52 PM CEST 
//


package uk.gov.legislation.namespaces.legislation;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded"&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Group" maxOccurs="unbounded"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Part" maxOccurs="unbounded"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Chapter" maxOccurs="unbounded"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Pblock" maxOccurs="unbounded"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}P1group" maxOccurs="unbounded"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}P1" maxOccurs="unbounded"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}P2group" maxOccurs="unbounded"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}P2" maxOccurs="unbounded"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}P" maxOccurs="unbounded"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Tabular"/&gt;
 *         &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Figure"/&gt;
 *         &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Form"/&gt;
 *         &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}IncludedDocument"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attGroup ref="{http://www.legislation.gov.uk/namespaces/legislation}PelementIDattributes"/&gt;
 *       &lt;attGroup ref="{http://www.legislation.gov.uk/namespaces/legislation}CommonSubAttributes"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "groupsAndPartsAndChapters"
})
@XmlRootElement(name = "AbstractBody")
public class AbstractBody {

    @XmlElements({
        @XmlElement(name = "Group", type = Group.class),
        @XmlElement(name = "Part", type = Part.class),
        @XmlElement(name = "Chapter", type = Chapter.class),
        @XmlElement(name = "Pblock", type = Pblock.class),
        @XmlElement(name = "P1group", type = P1Group.class),
        @XmlElement(name = "P1", type = P1 .class),
        @XmlElement(name = "P2group", type = P2Group.class),
        @XmlElement(name = "P2", type = P2 .class),
        @XmlElement(name = "P", type = P.class),
        @XmlElement(name = "Tabular", type = Tabular.class),
        @XmlElement(name = "Figure", type = Figure.class),
        @XmlElement(name = "Form", type = Form.class),
        @XmlElement(name = "IncludedDocument", type = IncludedDocument.class)
    })
    protected List<Object> groupsAndPartsAndChapters;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String id;
    @XmlAttribute(name = "shortId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String shortId;
    @XmlAttribute(name = "DocumentURI")
    @XmlSchemaType(name = "anyURI")
    protected String documentURI;
    @XmlAttribute(name = "IdURI")
    @XmlSchemaType(name = "anyURI")
    protected String idURI;
    @XmlAttribute(name = "NotesURI")
    @XmlSchemaType(name = "anyURI")
    protected String notesURI;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String lang;
    @XmlAttribute(name = "space", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String space;
    @XmlAttribute(name = "base", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlSchemaType(name = "anyURI")
    protected String base;
    @XmlAttribute(name = "AltVersionRefs")
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> altVersionRefs;

    /**
     * Gets the value of the groupsAndPartsAndChapters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the groupsAndPartsAndChapters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroupsAndPartsAndChapters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Group }
     * {@link Part }
     * {@link Chapter }
     * {@link Pblock }
     * {@link P1Group }
     * {@link P1 }
     * {@link P2Group }
     * {@link P2 }
     * {@link P }
     * {@link Tabular }
     * {@link Figure }
     * {@link Form }
     * {@link IncludedDocument }
     * 
     * 
     */
    public List<Object> getGroupsAndPartsAndChapters() {
        if (groupsAndPartsAndChapters == null) {
            groupsAndPartsAndChapters = new ArrayList<>();
        }
        return this.groupsAndPartsAndChapters;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the shortId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortId() {
        return shortId;
    }

    /**
     * Sets the value of the shortId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortId(String value) {
        this.shortId = value;
    }

    /**
     * Gets the value of the documentURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentURI() {
        return documentURI;
    }

    /**
     * Sets the value of the documentURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentURI(String value) {
        this.documentURI = value;
    }

    /**
     * Gets the value of the idURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdURI() {
        return idURI;
    }

    /**
     * Sets the value of the idURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdURI(String value) {
        this.idURI = value;
    }

    /**
     * Gets the value of the notesURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotesURI() {
        return notesURI;
    }

    /**
     * Sets the value of the notesURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotesURI(String value) {
        this.notesURI = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpace() {
        return space;
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpace(String value) {
        this.space = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

    /**
     * Gets the value of the altVersionRefs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the altVersionRefs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAltVersionRefs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAltVersionRefs() {
        if (altVersionRefs == null) {
            altVersionRefs = new ArrayList<>();
        }
        return this.altVersionRefs;
    }

}
