//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.07 at 06:17:52 PM CEST 
//


package uk.gov.legislation.namespaces.legislation;

import org.w3._1999.xhtml.Table;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;choice maxOccurs="unbounded"&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}PrimaryPreamble"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}SecondaryPreamble"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Text"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Body"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Group"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Part"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Chapter"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Pblock"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}PsubBlock"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Para"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}P1"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}P2"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}P3"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}P4"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}P5"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}P6"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}P7"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}P1para"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}P2para"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}P3para"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}P4para"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}P5para"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}P6para"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}P7para"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}P1group"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}P2group"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}P3group"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Schedules"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Schedule"/&gt;
 *           &lt;sequence&gt;
 *             &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}BlockAmendment"/&gt;
 *             &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}AppendText" minOccurs="0"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;element ref="{http://www.w3.org/1999/xhtml}table"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Contents"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}ContentsPart"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}ContentsChapter"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}ContentsPblock"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}ContentsPsubBlock"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}ContentsItem"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}ContentsSubItem"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}ContentsSchedules"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}ContentsSchedule"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}ContentsAppendix"/&gt;
 *           &lt;group ref="{http://www.legislation.gov.uk/namespaces/legislation}BlockBasic"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}FragmentNumber"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}FragmentTitle"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}IncludedDocument"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attGroup ref="{http://www.legislation.gov.uk/namespaces/legislation}StructureNumberFormattingAttributes"/&gt;
 *       &lt;attGroup ref="{http://www.legislation.gov.uk/namespaces/legislation}CommonAttributes"/&gt;
 *       &lt;attGroup ref="{http://www.legislation.gov.uk/namespaces/legislation}QuotesAttributes"/&gt;
 *       &lt;attGroup ref="{http://www.legislation.gov.uk/namespaces/legislation}LegislationAmendmentAttributes"/&gt;
 *       &lt;attribute name="PartialRefs"&gt;
 *         &lt;simpleType&gt;
 *           &lt;list itemType="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="CitationListRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "includedDocument",
    "primaryPreamblesAndSecondaryPreamblesAndTexts"
})
@XmlRootElement(name = "BlockAmendment")
public class BlockAmendment {

    @XmlElement(name = "IncludedDocument")
    protected IncludedDocument includedDocument;
    @XmlElements({
        @XmlElement(name = "PrimaryPreamble", type = PrimaryPreamble.class),
        @XmlElement(name = "SecondaryPreamble", type = SecondaryPreamble.class),
        @XmlElement(name = "Text", type = Text.class),
        @XmlElement(name = "Body", type = Body.class),
        @XmlElement(name = "Group", type = Group.class),
        @XmlElement(name = "Part", type = Part.class),
        @XmlElement(name = "Chapter", type = Chapter.class),
        @XmlElement(name = "Pblock", type = Pblock.class),
        @XmlElement(name = "PsubBlock", type = PsubBlock.class),
        @XmlElement(name = "Para", type = Para.class),
        @XmlElement(name = "P1", type = P1 .class),
        @XmlElement(name = "P2", type = P2 .class),
        @XmlElement(name = "P3", type = P3 .class),
        @XmlElement(name = "P4", type = P4 .class),
        @XmlElement(name = "P5", type = P5 .class),
        @XmlElement(name = "P6", type = P6 .class),
        @XmlElement(name = "P7", type = P7 .class),
        @XmlElement(name = "P1para", type = P1Para.class),
        @XmlElement(name = "P2para", type = P2Para.class),
        @XmlElement(name = "P3para", type = P3Para.class),
        @XmlElement(name = "P4para", type = P4Para.class),
        @XmlElement(name = "P5para", type = P5Para.class),
        @XmlElement(name = "P6para", type = P6Para.class),
        @XmlElement(name = "P7para", type = P7Para.class),
        @XmlElement(name = "P1group", type = P1Group.class),
        @XmlElement(name = "P2group", type = P2Group.class),
        @XmlElement(name = "P3group", type = P3Group.class),
        @XmlElement(name = "Schedules", type = Schedules.class),
        @XmlElement(name = "Schedule", type = Schedule.class),
        @XmlElement(name = "BlockAmendment", type = BlockAmendment.class),
        @XmlElement(name = "AppendText", type = AppendText.class),
        @XmlElement(name = "table", namespace = "http://www.w3.org/1999/xhtml", type = Table.class),
        @XmlElement(name = "Contents", type = Contents.class),
        @XmlElement(name = "ContentsPart", type = ContentsPart.class),
        @XmlElement(name = "ContentsChapter", type = ContentsChapter.class),
        @XmlElement(name = "ContentsPblock", type = ContentsPblock.class),
        @XmlElement(name = "ContentsPsubBlock", type = ContentsPsubBlock.class),
        @XmlElement(name = "ContentsItem", type = ContentsItem.class),
        @XmlElement(name = "ContentsSubItem", type = ContentsSubItem.class),
        @XmlElement(name = "ContentsSchedules", type = ContentsSchedules.class),
        @XmlElement(name = "ContentsSchedule", type = ContentsSchedule.class),
        @XmlElement(name = "ContentsAppendix", type = ContentsAppendix.class),
        @XmlElement(name = "P", type = P.class),
        @XmlElement(name = "OrderedList", type = OrderedList.class),
        @XmlElement(name = "UnorderedList", type = UnorderedList.class),
        @XmlElement(name = "DecoratedGroup", type = DecoratedGroup.class),
        @XmlElement(name = "KeyList", type = KeyList.class),
        @XmlElement(name = "Figure", type = Figure.class),
        @XmlElement(name = "Tabular", type = Tabular.class),
        @XmlElement(name = "Form", type = Form.class),
        @XmlElement(name = "Formula", type = Formula.class),
        @XmlElement(name = "FragmentNumber", type = FragmentNumber.class),
        @XmlElement(name = "FragmentTitle", type = FragmentTitle.class)
    })
    protected List<Object> primaryPreamblesAndSecondaryPreamblesAndTexts;
    @XmlAttribute(name = "PartialRefs")
    protected List<String> partialRefs;
    @XmlAttribute(name = "CitationListRef")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object citationListRef;
    @XmlAttribute(name = "NumberFormat")
    protected String numberFormat;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String id;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String lang;
    @XmlAttribute(name = "space", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String space;
    @XmlAttribute(name = "base", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlSchemaType(name = "anyURI")
    protected String base;
    @XmlAttribute(name = "AltVersionRefs")
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> altVersionRefs;
    @XmlAttribute(name = "Format", required = true)
    protected String format;
    @XmlAttribute(name = "TargetClass", required = true)
    protected String targetClass;
    @XmlAttribute(name = "TargetSubClass", required = true)
    protected MinorType targetSubClass;
    @XmlAttribute(name = "Context", required = true)
    protected String context;

    /**
     * Gets the value of the includedDocument property.
     * 
     * @return
     *     possible object is
     *     {@link IncludedDocument }
     *     
     */
    public IncludedDocument getIncludedDocument() {
        return includedDocument;
    }

    /**
     * Sets the value of the includedDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncludedDocument }
     *     
     */
    public void setIncludedDocument(IncludedDocument value) {
        this.includedDocument = value;
    }

    /**
     * Gets the value of the primaryPreamblesAndSecondaryPreamblesAndTexts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the primaryPreamblesAndSecondaryPreamblesAndTexts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrimaryPreamblesAndSecondaryPreamblesAndTexts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PrimaryPreamble }
     * {@link SecondaryPreamble }
     * {@link Text }
     * {@link Body }
     * {@link Group }
     * {@link Part }
     * {@link Chapter }
     * {@link Pblock }
     * {@link PsubBlock }
     * {@link Para }
     * {@link P1 }
     * {@link P2 }
     * {@link P3 }
     * {@link P4 }
     * {@link P5 }
     * {@link P6 }
     * {@link P7 }
     * {@link P1Para }
     * {@link P2Para }
     * {@link P3Para }
     * {@link P4Para }
     * {@link P5Para }
     * {@link P6Para }
     * {@link P7Para }
     * {@link P1Group }
     * {@link P2Group }
     * {@link P3Group }
     * {@link Schedules }
     * {@link Schedule }
     * {@link BlockAmendment }
     * {@link AppendText }
     * {@link Table }
     * {@link Contents }
     * {@link ContentsPart }
     * {@link ContentsChapter }
     * {@link ContentsPblock }
     * {@link ContentsPsubBlock }
     * {@link ContentsItem }
     * {@link ContentsSubItem }
     * {@link ContentsSchedules }
     * {@link ContentsSchedule }
     * {@link ContentsAppendix }
     * {@link P }
     * {@link OrderedList }
     * {@link UnorderedList }
     * {@link DecoratedGroup }
     * {@link KeyList }
     * {@link Figure }
     * {@link Tabular }
     * {@link Form }
     * {@link Formula }
     * {@link FragmentNumber }
     * {@link FragmentTitle }
     * 
     * 
     */
    public List<Object> getPrimaryPreamblesAndSecondaryPreamblesAndTexts() {
        if (primaryPreamblesAndSecondaryPreamblesAndTexts == null) {
            primaryPreamblesAndSecondaryPreamblesAndTexts = new ArrayList<>();
        }
        return this.primaryPreamblesAndSecondaryPreamblesAndTexts;
    }

    /**
     * Gets the value of the partialRefs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partialRefs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartialRefs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPartialRefs() {
        if (partialRefs == null) {
            partialRefs = new ArrayList<>();
        }
        return this.partialRefs;
    }

    /**
     * Gets the value of the citationListRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCitationListRef() {
        return citationListRef;
    }

    /**
     * Sets the value of the citationListRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCitationListRef(Object value) {
        this.citationListRef = value;
    }

    /**
     * Gets the value of the numberFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberFormat() {
        if (numberFormat == null) {
            return "default";
        } else {
            return numberFormat;
        }
    }

    /**
     * Sets the value of the numberFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberFormat(String value) {
        this.numberFormat = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpace() {
        return space;
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpace(String value) {
        this.space = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

    /**
     * Gets the value of the altVersionRefs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the altVersionRefs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAltVersionRefs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAltVersionRefs() {
        if (altVersionRefs == null) {
            altVersionRefs = new ArrayList<>();
        }
        return this.altVersionRefs;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormat(String value) {
        this.format = value;
    }

    /**
     * Gets the value of the targetClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetClass() {
        return targetClass;
    }

    /**
     * Sets the value of the targetClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetClass(String value) {
        this.targetClass = value;
    }

    /**
     * Gets the value of the targetSubClass property.
     * 
     * @return
     *     possible object is
     *     {@link MinorType }
     *     
     */
    public MinorType getTargetSubClass() {
        return targetSubClass;
    }

    /**
     * Sets the value of the targetSubClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link MinorType }
     *     
     */
    public void setTargetSubClass(MinorType value) {
        this.targetSubClass = value;
    }

    /**
     * Gets the value of the context property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContext() {
        return context;
    }

    /**
     * Sets the value of the context property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContext(String value) {
        this.context = value;
    }

}
