//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.07 at 06:17:52 PM CEST 
//


package uk.gov.legislation.namespaces.legislation;

import uk.co.tso.assets.namespace.error.ErrorType;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;group ref="{http://www.legislation.gov.uk/namespaces/legislation}InlineLegislationCitation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attGroup ref="{http://www.legislation.gov.uk/namespaces/legislation}CitationElementIDAttributes"/&gt;
 *       &lt;attGroup ref="{http://www.legislation.gov.uk/namespaces/legislation}CommonSubAttributes"/&gt;
 *       &lt;attribute name="URI" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *       &lt;attribute name="Class" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="EnglandAct"/&gt;
 *             &lt;enumeration value="GreatBritainAct"/&gt;
 *             &lt;enumeration value="IrelandAct"/&gt;
 *             &lt;enumeration value="NorthernIrelandAct"/&gt;
 *             &lt;enumeration value="NorthernIrelandAssemblyMeasure"/&gt;
 *             &lt;enumeration value="NorthernIrelandParliamentAct"/&gt;
 *             &lt;enumeration value="NorthernIrelandOrderInCouncil"/&gt;
 *             &lt;enumeration value="NorthernIrelandStatutoryRule"/&gt;
 *             &lt;enumeration value="ScottishAct"/&gt;
 *             &lt;enumeration value="ScottishOldAct"/&gt;
 *             &lt;enumeration value="ScottishStatutoryInstrument"/&gt;
 *             &lt;enumeration value="UnitedKingdomChurchMeasure"/&gt;
 *             &lt;enumeration value="UnitedKingdomPrivateAct"/&gt;
 *             &lt;enumeration value="UnitedKingdomPublicGeneralAct"/&gt;
 *             &lt;enumeration value="UnitedKingdomLocalAct"/&gt;
 *             &lt;enumeration value="UnitedKingdomStatutoryInstrument"/&gt;
 *             &lt;enumeration value="WelshAssemblyMeasure"/&gt;
 *             &lt;enumeration value="WelshNationalAssemblyAct"/&gt;
 *             &lt;enumeration value="WelshStatutoryInstrument"/&gt;
 *             &lt;enumeration value="UnitedKingdomChurchInstrument"/&gt;
 *             &lt;enumeration value="EuropeanUnion"/&gt;
 *             &lt;enumeration value="EuropeanEconomicCommunity"/&gt;
 *             &lt;enumeration value="EuropeanUnionRegulation"/&gt;
 *             &lt;enumeration value="EuropeanEconomicCommunityRegulation"/&gt;
 *             &lt;enumeration value="EuropeanUnionDirective"/&gt;
 *             &lt;enumeration value="EuropeanEconomicCommunityDirective"/&gt;
 *             &lt;enumeration value="EuropeanUnionDecision"/&gt;
 *             &lt;enumeration value="EuropeanEconomicCommunityDecision"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="Locator" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DOI" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Year" use="required" type="{http://www.w3.org/2001/XMLSchema}gYear" /&gt;
 *       &lt;attribute name="Number" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="Date" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="Title" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SectionRef" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="StartSectionRef" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="EndSectionRef" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="AlternativeNumber" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CommentaryRef" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="StartDate" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="EndDate" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="Prospective" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "Citation")
public class Citation {

    @XmlElementRefs({
        @XmlElementRef(name = "Addition", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Proviso", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Proviso.class, required = false),
        @XmlElementRef(name = "Term", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Term.class, required = false),
        @XmlElementRef(name = "Emphasis", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Emphasis.class, required = false),
        @XmlElementRef(name = "InlineAmendment", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = InlineAmendment.class, required = false),
        @XmlElementRef(name = "CommentaryRef", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = CommentaryRef.class, required = false),
        @XmlElementRef(name = "MarginNoteRef", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = MarginNoteRef.class, required = false),
        @XmlElementRef(name = "Error", namespace = "http://www.tso.co.uk/assets/namespace/error", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Span", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Acronym", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Acronym.class, required = false),
        @XmlElementRef(name = "Character", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Character.class, required = false),
        @XmlElementRef(name = "SmallCaps", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = SmallCaps.class, required = false),
        @XmlElementRef(name = "Underline", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Superior", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "FootnoteRef", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = FootnoteRef.class, required = false),
        @XmlElementRef(name = "Abbreviation", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Abbreviation.class, required = false),
        @XmlElementRef(name = "Repeal", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Repeal.class, required = false),
        @XmlElementRef(name = "Substitution", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Strong", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Strong.class, required = false),
        @XmlElementRef(name = "Warning", namespace = "http://www.tso.co.uk/assets/namespace/error", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Definition", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Definition.class, required = false),
        @XmlElementRef(name = "Inferior", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = JAXBElement.class, required = false)
    })
    @XmlMixed
    protected List<Object> content;
    @XmlAttribute(name = "URI")
    @XmlSchemaType(name = "anyURI")
    protected String uri;
    @XmlAttribute(name = "Class", required = true)
    protected String clazz;
    @XmlAttribute(name = "Locator")
    protected String locator;
    @XmlAttribute(name = "DOI")
    protected String doi;
    @XmlAttribute(name = "Year", required = true)
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar year;
    @XmlAttribute(name = "Number")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger number;
    @XmlAttribute(name = "Date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlAttribute(name = "Title")
    protected String title;
    @XmlAttribute(name = "SectionRef")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String sectionRef;
    @XmlAttribute(name = "StartSectionRef")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String startSectionRef;
    @XmlAttribute(name = "EndSectionRef")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String endSectionRef;
    @XmlAttribute(name = "AlternativeNumber")
    protected String alternativeNumber;
    @XmlAttribute(name = "CommentaryRef")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String commentaryRef;
    @XmlAttribute(name = "StartDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startDate;
    @XmlAttribute(name = "EndDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endDate;
    @XmlAttribute(name = "Prospective")
    protected Boolean prospective;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String lang;
    @XmlAttribute(name = "space", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String space;
    @XmlAttribute(name = "base", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlSchemaType(name = "anyURI")
    protected String base;
    @XmlAttribute(name = "AltVersionRefs")
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> altVersionRefs;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link ChangeType }{@code >}
     * {@link String }
     * {@link Proviso }
     * {@link Emphasis }
     * {@link Term }
     * {@link InlineAmendment }
     * {@link CommentaryRef }
     * {@link JAXBElement }{@code <}{@link ErrorType }{@code >}
     * {@link MarginNoteRef }
     * {@link JAXBElement }{@code <}{@link InlineStructure }{@code >}
     * {@link Acronym }
     * {@link Character }
     * {@link JAXBElement }{@code <}{@link InlineStructure }{@code >}
     * {@link SmallCaps }
     * {@link JAXBElement }{@code <}{@link InlineStructure }{@code >}
     * {@link FootnoteRef }
     * {@link Abbreviation }
     * {@link Repeal }
     * {@link Strong }
     * {@link JAXBElement }{@code <}{@link ChangeType }{@code >}
     * {@link JAXBElement }{@code <}{@link ErrorType }{@code >}
     * {@link JAXBElement }{@code <}{@link InlineStructure }{@code >}
     * {@link Definition }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<>();
        }
        return this.content;
    }

    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURI() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURI(String value) {
        this.uri = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the locator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocator() {
        return locator;
    }

    /**
     * Sets the value of the locator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocator(String value) {
        this.locator = value;
    }

    /**
     * Gets the value of the doi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOI() {
        return doi;
    }

    /**
     * Sets the value of the doi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOI(String value) {
        this.doi = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setYear(XMLGregorianCalendar value) {
        this.year = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumber(BigInteger value) {
        this.number = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the sectionRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSectionRef() {
        return sectionRef;
    }

    /**
     * Sets the value of the sectionRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSectionRef(String value) {
        this.sectionRef = value;
    }

    /**
     * Gets the value of the startSectionRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartSectionRef() {
        return startSectionRef;
    }

    /**
     * Sets the value of the startSectionRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartSectionRef(String value) {
        this.startSectionRef = value;
    }

    /**
     * Gets the value of the endSectionRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndSectionRef() {
        return endSectionRef;
    }

    /**
     * Sets the value of the endSectionRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndSectionRef(String value) {
        this.endSectionRef = value;
    }

    /**
     * Gets the value of the alternativeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternativeNumber() {
        return alternativeNumber;
    }

    /**
     * Sets the value of the alternativeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternativeNumber(String value) {
        this.alternativeNumber = value;
    }

    /**
     * Gets the value of the commentaryRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommentaryRef() {
        return commentaryRef;
    }

    /**
     * Sets the value of the commentaryRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommentaryRef(String value) {
        this.commentaryRef = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the prospective property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isProspective() {
        if (prospective == null) {
            return false;
        } else {
            return prospective;
        }
    }

    /**
     * Sets the value of the prospective property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setProspective(Boolean value) {
        this.prospective = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpace() {
        return space;
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpace(String value) {
        this.space = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

    /**
     * Gets the value of the altVersionRefs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the altVersionRefs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAltVersionRefs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAltVersionRefs() {
        if (altVersionRefs == null) {
            altVersionRefs = new ArrayList<>();
        }
        return this.altVersionRefs;
    }

}
