//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.07 at 06:17:52 PM CEST 
//


package uk.gov.legislation.namespaces.legislation;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CommentaryType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CommentaryType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="X"/&gt;
 *     &lt;enumeration value="F"/&gt;
 *     &lt;enumeration value="I"/&gt;
 *     &lt;enumeration value="C"/&gt;
 *     &lt;enumeration value="M"/&gt;
 *     &lt;enumeration value="E"/&gt;
 *     &lt;enumeration value="P"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CommentaryType")
@XmlEnum
public enum CommentaryType {


    /**
     * The X-note annotation type is used sparingly to alert users to anything they may need to be aware of in using the text.
     * 
     */
    X,

    /**
     * ‘F’ stands for ‘Footnotes’. This annotation type is used for amendments, including repeals, where there is authority to change the text.
     * 
     */
    F,

    /**
     * ‘I’ stands for ‘In-force’. This annotation type contains information about the coming into force of a provision and will typically state whether it is partly or wholly in force, give the date or dates of commencement and cite relevant provisions of the Act and any commencing instruments.
     * 
     */
    I,

    /**
     * ‘C’ stands for ‘Cross-notes’, so called because of the way in which they were presented in the hard copy predecessors to SLD. This annotation type is used to denote the effect when the meaning, scope or application of an Act or provision etc. is changed in some way, but without there being any authority to alter the text.
     * 
     */
    C,

    /**
     * This annotation type is so called because it used to appear in the margin of the Queen’s Printer’s copy of primary legislation. M-notes recite the year and number of an Act or instrument mentioned in the text.
     * 
     */
    M,

    /**
     * This annotation type contains information about the geographic extent of the Act or relevant part of it.
     * 
     */
    E,

    /**
     * ‘P’ stands for ‘Power exercised’. Where a provision of primary legislation confers power to make subordinate legislation and that power is exercised (i.e. an instrument is made in pursuance of it), that exercise may be recorded in a P-note. The annotation will cite any instruments made under that power.
     * 
     */
    P;

    public static CommentaryType fromValue(String v) {
        return valueOf(v);
    }

    public String value() {
        return name();
    }

}
