//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.07 at 06:17:52 PM CEST 
//


package uk.gov.legislation.namespaces.legislation;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.w3._1998.math.mathml.Math;
import org.w3._1999.xhtml.Table;
import uk.co.tso.assets.namespace.error.ErrorType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://www.legislation.gov.uk/namespaces/legislation}TableCell" maxOccurs="unbounded"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "strongsAndEmphasisesAndInferiors"
})
@XmlRootElement(name = "GroupItem")
public class GroupItem {

    @XmlElementRefs({
        @XmlElementRef(name = "ExternalLink", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = ExternalLink.class, required = false),
        @XmlElementRef(name = "Addition", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "table", namespace = "http://www.w3.org/1999/xhtml", type = Table.class, required = false),
        @XmlElementRef(name = "math", namespace = "http://www.w3.org/1998/Math/MathML", type = Math.class, required = false),
        @XmlElementRef(name = "MarginNoteRef", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = MarginNoteRef.class, required = false),
        @XmlElementRef(name = "Acronym", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Acronym.class, required = false),
        @XmlElementRef(name = "Form", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Form.class, required = false),
        @XmlElementRef(name = "P3", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = P3 .class, required = false),
        @XmlElementRef(name = "P5", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = P5 .class, required = false),
        @XmlElementRef(name = "CitationListRef", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = CitationListRef.class, required = false),
        @XmlElementRef(name = "Abbreviation", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Abbreviation.class, required = false),
        @XmlElementRef(name = "Strong", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Strong.class, required = false),
        @XmlElementRef(name = "Para", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Para.class, required = false),
        @XmlElementRef(name = "Emphasis", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Emphasis.class, required = false),
        @XmlElementRef(name = "Term", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Term.class, required = false),
        @XmlElementRef(name = "Image", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Image.class, required = false),
        @XmlElementRef(name = "InlineExtract", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = InlineExtract.class, required = false),
        @XmlElementRef(name = "KeyList", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = KeyList.class, required = false),
        @XmlElementRef(name = "Figure", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Figure.class, required = false),
        @XmlElementRef(name = "P3group", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = P3Group.class, required = false),
        @XmlElementRef(name = "Error", namespace = "http://www.tso.co.uk/assets/namespace/error", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Span", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Character", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Character.class, required = false),
        @XmlElementRef(name = "Citation", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Citation.class, required = false),
        @XmlElementRef(name = "Underline", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Substitution", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "OrderedList", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = OrderedList.class, required = false),
        @XmlElementRef(name = "Proviso", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Proviso.class, required = false),
        @XmlElementRef(name = "DecoratedGroup", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = DecoratedGroup.class, required = false),
        @XmlElementRef(name = "InlineAmendment", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = InlineAmendment.class, required = false),
        @XmlElementRef(name = "CommentaryRef", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = CommentaryRef.class, required = false),
        @XmlElementRef(name = "P6", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = P6 .class, required = false),
        @XmlElementRef(name = "P4", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = P4 .class, required = false),
        @XmlElementRef(name = "InternalLink", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = InternalLink.class, required = false),
        @XmlElementRef(name = "P2", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = P2 .class, required = false),
        @XmlElementRef(name = "UnorderedList", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = UnorderedList.class, required = false),
        @XmlElementRef(name = "P2group", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = P2Group.class, required = false),
        @XmlElementRef(name = "Warning", namespace = "http://www.tso.co.uk/assets/namespace/error", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Inferior", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "P", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = P.class, required = false),
        @XmlElementRef(name = "P1", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = P1 .class, required = false),
        @XmlElementRef(name = "Tabular", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Tabular.class, required = false),
        @XmlElementRef(name = "Formula", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Formula.class, required = false),
        @XmlElementRef(name = "P7", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = P7 .class, required = false),
        @XmlElementRef(name = "CitationSubRef", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = CitationSubRef.class, required = false),
        @XmlElementRef(name = "SmallCaps", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = SmallCaps.class, required = false),
        @XmlElementRef(name = "Superior", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "FootnoteRef", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = FootnoteRef.class, required = false),
        @XmlElementRef(name = "Repeal", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Repeal.class, required = false),
        @XmlElementRef(name = "Definition", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = Definition.class, required = false),
        @XmlElementRef(name = "P1group", namespace = "http://www.legislation.gov.uk/namespaces/legislation", type = P1Group.class, required = false)
    })
    protected List<Object> strongsAndEmphasisesAndInferiors;

    /**
     * Gets the value of the strongsAndEmphasisesAndInferiors property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the strongsAndEmphasisesAndInferiors property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStrongsAndEmphasisesAndInferiors().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExternalLink }
     * {@link JAXBElement }{@code <}{@link ChangeType }{@code >}
     * {@link Table }
     * {@link Math }
     * {@link MarginNoteRef }
     * {@link Acronym }
     * {@link Form }
     * {@link P3 }
     * {@link P5 }
     * {@link CitationListRef }
     * {@link Abbreviation }
     * {@link Strong }
     * {@link Para }
     * {@link Emphasis }
     * {@link Term }
     * {@link Image }
     * {@link InlineExtract }
     * {@link KeyList }
     * {@link Figure }
     * {@link P3Group }
     * {@link JAXBElement }{@code <}{@link ErrorType }{@code >}
     * {@link JAXBElement }{@code <}{@link InlineStructure }{@code >}
     * {@link Character }
     * {@link Citation }
     * {@link JAXBElement }{@code <}{@link InlineStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link ChangeType }{@code >}
     * {@link OrderedList }
     * {@link Proviso }
     * {@link DecoratedGroup }
     * {@link InlineAmendment }
     * {@link CommentaryRef }
     * {@link P6 }
     * {@link P4 }
     * {@link InternalLink }
     * {@link P2 }
     * {@link UnorderedList }
     * {@link P2Group }
     * {@link JAXBElement }{@code <}{@link ErrorType }{@code >}
     * {@link JAXBElement }{@code <}{@link InlineStructure }{@code >}
     * {@link P }
     * {@link P1 }
     * {@link Tabular }
     * {@link Formula }
     * {@link P7 }
     * {@link CitationSubRef }
     * {@link SmallCaps }
     * {@link JAXBElement }{@code <}{@link InlineStructure }{@code >}
     * {@link FootnoteRef }
     * {@link Repeal }
     * {@link P1Group }
     * {@link Definition }
     * 
     * 
     */
    public List<Object> getStrongsAndEmphasisesAndInferiors() {
        if (strongsAndEmphasisesAndInferiors == null) {
            strongsAndEmphasisesAndInferiors = new ArrayList<Object>();
        }
        return this.strongsAndEmphasisesAndInferiors;
    }

}
