//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.07 at 06:17:52 PM CEST 
//


package uk.gov.legislation.namespaces.legislation;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import uk.gov.legislation.namespaces.metadata.Metadata;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}Metadata" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;sequence>
 *             &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Contents"/>
 *             &lt;sequence minOccurs="0">
 *               &lt;choice>
 *                 &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Primary"/>
 *                 &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Secondary"/>
 *               &lt;/choice>
 *               &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Footnotes" minOccurs="0"/>
 *               &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}MarginNotes" minOccurs="0"/>
 *               &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Versions" minOccurs="0"/>
 *               &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Resources" minOccurs="0"/>
 *               &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Commentaries" minOccurs="0"/>
 *               &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}CitationLists" minOccurs="0"/>
 *             &lt;/sequence>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;choice>
 *               &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Primary"/>
 *               &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Secondary"/>
 *             &lt;/choice>
 *             &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Footnotes" minOccurs="0"/>
 *             &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}MarginNotes" minOccurs="0"/>
 *             &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Versions" minOccurs="0"/>
 *             &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Resources" minOccurs="0"/>
 *             &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}Commentaries" minOccurs="0"/>
 *             &lt;element ref="{http://www.legislation.gov.uk/namespaces/legislation}CitationLists" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.tso.co.uk/assets/namespace/error}ErrorAttributes"/>
 *       &lt;attGroup ref="{http://www.legislation.gov.uk/namespaces/legislation}FragmentAttributes"/>
 *       &lt;attGroup ref="{http://www.legislation.gov.uk/namespaces/legislation}CommonAttributes"/>
 *       &lt;attribute name="SchemaVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" fixed="1.0" />
 *       &lt;attribute name="DocumentURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="IdURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metadata",
    "contents",
    "secondary",
    "primary",
    "footnotes",
    "marginNotes",
    "versions",
    "resources",
    "commentaries",
    "citationLists"
})
@XmlRootElement(name = "Legislation")
public class Legislation {

    @XmlElement(name = "Metadata", namespace = "http://www.legislation.gov.uk/namespaces/metadata")
    protected Metadata metadata;
    @XmlElement(name = "Contents")
    protected Contents contents;
    @XmlElement(name = "Secondary")
    protected Secondary secondary;
    @XmlElement(name = "Primary")
    protected Primary primary;
    @XmlElement(name = "Footnotes")
    protected Footnotes footnotes;
    @XmlElement(name = "MarginNotes")
    protected MarginNotes marginNotes;
    @XmlElement(name = "Versions")
    protected Versions versions;
    @XmlElement(name = "Resources")
    protected Resources resources;
    @XmlElement(name = "Commentaries")
    protected Commentaries commentaries;
    @XmlElement(name = "CitationLists")
    protected CitationLists citationLists;
    @XmlAttribute(name = "SchemaVersion", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String schemaVersion;
    @XmlAttribute(name = "DocumentURI")
    @XmlSchemaType(name = "anyURI")
    protected String documentURI;
    @XmlAttribute(name = "IdURI")
    @XmlSchemaType(name = "anyURI")
    protected String idURI;
    @XmlAttribute(name = "Date", namespace = "http://www.tso.co.uk/assets/namespace/error")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlAttribute(name = "Time", namespace = "http://www.tso.co.uk/assets/namespace/error")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar time;
    @XmlAttribute(name = "FragmentId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String fragmentId;
    @XmlAttribute(name = "Version")
    protected BigInteger version;
    @XmlAttribute(name = "RestrictExtent")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String restrictExtent;
    @XmlAttribute(name = "RestrictStartDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar restrictStartDate;
    @XmlAttribute(name = "RestrictEndDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar restrictEndDate;
    @XmlAttribute(name = "Status")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String status;
    @XmlAttribute(name = "ConfersPower")
    protected Boolean confersPower;
    @XmlAttribute(name = "BlanketAmendment")
    protected Boolean blanketAmendment;
    @XmlAttribute(name = "Concurrent")
    protected Boolean concurrent;
    @XmlAttribute(name = "Match")
    protected Boolean match;
    @XmlAttribute(name = "AltDates")
    @XmlSchemaType(name = "anySimpleType")
    protected String altDates;
    @XmlAttribute(name = "NumberOfProvisions")
    protected BigInteger numberOfProvisions;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String id;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String lang;
    @XmlAttribute(name = "space", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String space;
    @XmlAttribute(name = "base", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlSchemaType(name = "anyURI")
    protected String base;
    @XmlAttribute(name = "AltVersionRefs")
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> altVersionRefs;

    /**
     * Gets the value of the metadata property.
     * 
     * @return
     *     possible object is
     *     {@link Metadata }
     *     
     */
    public Metadata getMetadata() {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Metadata }
     *     
     */
    public void setMetadata(Metadata value) {
        this.metadata = value;
    }

    /**
     * Gets the value of the contents property.
     * 
     * @return
     *     possible object is
     *     {@link Contents }
     *     
     */
    public Contents getContents() {
        return contents;
    }

    /**
     * Sets the value of the contents property.
     * 
     * @param value
     *     allowed object is
     *     {@link Contents }
     *     
     */
    public void setContents(Contents value) {
        this.contents = value;
    }

    /**
     * Gets the value of the secondary property.
     * 
     * @return
     *     possible object is
     *     {@link Secondary }
     *     
     */
    public Secondary getSecondary() {
        return secondary;
    }

    /**
     * Sets the value of the secondary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Secondary }
     *     
     */
    public void setSecondary(Secondary value) {
        this.secondary = value;
    }

    /**
     * Gets the value of the primary property.
     * 
     * @return
     *     possible object is
     *     {@link Primary }
     *     
     */
    public Primary getPrimary() {
        return primary;
    }

    /**
     * Sets the value of the primary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Primary }
     *     
     */
    public void setPrimary(Primary value) {
        this.primary = value;
    }

    /**
     * Gets the value of the footnotes property.
     * 
     * @return
     *     possible object is
     *     {@link Footnotes }
     *     
     */
    public Footnotes getFootnotes() {
        return footnotes;
    }

    /**
     * Sets the value of the footnotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Footnotes }
     *     
     */
    public void setFootnotes(Footnotes value) {
        this.footnotes = value;
    }

    /**
     * Gets the value of the marginNotes property.
     * 
     * @return
     *     possible object is
     *     {@link MarginNotes }
     *     
     */
    public MarginNotes getMarginNotes() {
        return marginNotes;
    }

    /**
     * Sets the value of the marginNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarginNotes }
     *     
     */
    public void setMarginNotes(MarginNotes value) {
        this.marginNotes = value;
    }

    /**
     * Gets the value of the versions property.
     * 
     * @return
     *     possible object is
     *     {@link Versions }
     *     
     */
    public Versions getVersions() {
        return versions;
    }

    /**
     * Sets the value of the versions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Versions }
     *     
     */
    public void setVersions(Versions value) {
        this.versions = value;
    }

    /**
     * Gets the value of the resources property.
     * 
     * @return
     *     possible object is
     *     {@link Resources }
     *     
     */
    public Resources getResources() {
        return resources;
    }

    /**
     * Sets the value of the resources property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resources }
     *     
     */
    public void setResources(Resources value) {
        this.resources = value;
    }

    /**
     * Gets the value of the commentaries property.
     * 
     * @return
     *     possible object is
     *     {@link Commentaries }
     *     
     */
    public Commentaries getCommentaries() {
        return commentaries;
    }

    /**
     * Sets the value of the commentaries property.
     * 
     * @param value
     *     allowed object is
     *     {@link Commentaries }
     *     
     */
    public void setCommentaries(Commentaries value) {
        this.commentaries = value;
    }

    /**
     * Gets the value of the citationLists property.
     * 
     * @return
     *     possible object is
     *     {@link CitationLists }
     *     
     */
    public CitationLists getCitationLists() {
        return citationLists;
    }

    /**
     * Sets the value of the citationLists property.
     * 
     * @param value
     *     allowed object is
     *     {@link CitationLists }
     *     
     */
    public void setCitationLists(CitationLists value) {
        this.citationLists = value;
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVersion() {
        if (schemaVersion == null) {
            return "1.0";
        } else {
            return schemaVersion;
        }
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVersion(String value) {
        this.schemaVersion = value;
    }

    /**
     * Gets the value of the documentURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentURI() {
        return documentURI;
    }

    /**
     * Sets the value of the documentURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentURI(String value) {
        this.documentURI = value;
    }

    /**
     * Gets the value of the idURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdURI() {
        return idURI;
    }

    /**
     * Sets the value of the idURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdURI(String value) {
        this.idURI = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTime(XMLGregorianCalendar value) {
        this.time = value;
    }

    /**
     * Gets the value of the fragmentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFragmentId() {
        return fragmentId;
    }

    /**
     * Sets the value of the fragmentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFragmentId(String value) {
        this.fragmentId = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersion(BigInteger value) {
        this.version = value;
    }

    /**
     * Gets the value of the restrictExtent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestrictExtent() {
        return restrictExtent;
    }

    /**
     * Sets the value of the restrictExtent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestrictExtent(String value) {
        this.restrictExtent = value;
    }

    /**
     * Gets the value of the restrictStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRestrictStartDate() {
        return restrictStartDate;
    }

    /**
     * Sets the value of the restrictStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRestrictStartDate(XMLGregorianCalendar value) {
        this.restrictStartDate = value;
    }

    /**
     * Gets the value of the restrictEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRestrictEndDate() {
        return restrictEndDate;
    }

    /**
     * Sets the value of the restrictEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRestrictEndDate(XMLGregorianCalendar value) {
        this.restrictEndDate = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the confersPower property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isConfersPower() {
        if (confersPower == null) {
            return false;
        } else {
            return confersPower;
        }
    }

    /**
     * Sets the value of the confersPower property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setConfersPower(Boolean value) {
        this.confersPower = value;
    }

    /**
     * Gets the value of the blanketAmendment property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isBlanketAmendment() {
        if (blanketAmendment == null) {
            return false;
        } else {
            return blanketAmendment;
        }
    }

    /**
     * Sets the value of the blanketAmendment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBlanketAmendment(Boolean value) {
        this.blanketAmendment = value;
    }

    /**
     * Gets the value of the concurrent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isConcurrent() {
        if (concurrent == null) {
            return false;
        } else {
            return concurrent;
        }
    }

    /**
     * Sets the value of the concurrent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setConcurrent(Boolean value) {
        this.concurrent = value;
    }

    /**
     * Gets the value of the match property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isMatch() {
        if (match == null) {
            return true;
        } else {
            return match;
        }
    }

    /**
     * Sets the value of the match property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMatch(Boolean value) {
        this.match = value;
    }

    /**
     * Gets the value of the altDates property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAltDates() {
        return altDates;
    }

    /**
     * Sets the value of the altDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAltDates(String value) {
        this.altDates = value;
    }

    /**
     * Gets the value of the numberOfProvisions property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfProvisions() {
        return numberOfProvisions;
    }

    /**
     * Sets the value of the numberOfProvisions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfProvisions(BigInteger value) {
        this.numberOfProvisions = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpace() {
        return space;
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpace(String value) {
        this.space = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

    /**
     * Gets the value of the altVersionRefs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the altVersionRefs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAltVersionRefs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAltVersionRefs() {
        if (altVersionRefs == null) {
            altVersionRefs = new ArrayList<Object>();
        }
        return this.altVersionRefs;
    }

}
