//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.07 at 06:17:52 PM CEST 
//


package uk.gov.legislation.namespaces.legislation;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.legislation.gov.uk/namespaces/legislation}ParaBasicStructure"&gt;
 *       &lt;attribute name="NumberOverride" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "ListItem")
public class ListItem
    extends ParaBasicStructure
{

    @XmlAttribute(name = "NumberOverride")
    protected String numberOverride;

    /**
     * Gets the value of the numberOverride property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOverride() {
        return numberOverride;
    }

    /**
     * Sets the value of the numberOverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOverride(String value) {
        this.numberOverride = value;
    }

}
