//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.07 at 06:17:52 PM CEST 
//


package uk.gov.legislation.namespaces.legislation;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.gov.legislation.namespaces.legislation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TermUnderlineSuperior_QNAME = new QName("http://www.legislation.gov.uk/namespaces/legislation", "Superior");
    private final static QName _TermUnderlineInferior_QNAME = new QName("http://www.legislation.gov.uk/namespaces/legislation", "Inferior");
    private final static QName _TermUnderlineSmallCaps_QNAME = new QName("http://www.legislation.gov.uk/namespaces/legislation", "SmallCaps");
    private final static QName _TermUnderlineEmphasis_QNAME = new QName("http://www.legislation.gov.uk/namespaces/legislation", "Emphasis");
    private final static QName _TermUnderlineStrong_QNAME = new QName("http://www.legislation.gov.uk/namespaces/legislation", "Strong");
    private final static QName _ContentsNumber_QNAME = new QName("http://www.legislation.gov.uk/namespaces/legislation", "ContentsNumber");
    private final static QName _Title_QNAME = new QName("http://www.legislation.gov.uk/namespaces/legislation", "Title");
    private final static QName _Span_QNAME = new QName("http://www.legislation.gov.uk/namespaces/legislation", "Span");
    private final static QName _Underline_QNAME = new QName("http://www.legislation.gov.uk/namespaces/legislation", "Underline");
    private final static QName _Key_QNAME = new QName("http://www.legislation.gov.uk/namespaces/legislation", "Key");
    private final static QName _PersonName_QNAME = new QName("http://www.legislation.gov.uk/namespaces/legislation", "PersonName");
    private final static QName _Subtitle_QNAME = new QName("http://www.legislation.gov.uk/namespaces/legislation", "Subtitle");
    private final static QName _JobTitle_QNAME = new QName("http://www.legislation.gov.uk/namespaces/legislation", "JobTitle");
    private final static QName _Approved_QNAME = new QName("http://www.legislation.gov.uk/namespaces/legislation", "Approved");
    private final static QName _DateText_QNAME = new QName("http://www.legislation.gov.uk/namespaces/legislation", "DateText");
    private final static QName _Addition_QNAME = new QName("http://www.legislation.gov.uk/namespaces/legislation", "Addition");
    private final static QName _Department_QNAME = new QName("http://www.legislation.gov.uk/namespaces/legislation", "Department");
    private final static QName _Correction_QNAME = new QName("http://www.legislation.gov.uk/namespaces/legislation", "Correction");
    private final static QName _Number_QNAME = new QName("http://www.legislation.gov.uk/namespaces/legislation", "Number");
    private final static QName _Reference_QNAME = new QName("http://www.legislation.gov.uk/namespaces/legislation", "Reference");
    private final static QName _Substitution_QNAME = new QName("http://www.legislation.gov.uk/namespaces/legislation", "Substitution");
    private final static QName _Draft_QNAME = new QName("http://www.legislation.gov.uk/namespaces/legislation", "Draft");
    private final static QName _LongTitle_QNAME = new QName("http://www.legislation.gov.uk/namespaces/legislation", "LongTitle");
    private final static QName _SubjectInformationSubject_QNAME = new QName("http://www.legislation.gov.uk/namespaces/legislation", "Subject");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.gov.legislation.namespaces.legislation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Term }
     * 
     */
    public Term createTerm() {
        return new Term();
    }

    /**
     * Create an instance of {@link Tabular }
     * 
     */
    public Tabular createTabular() {
        return new Tabular();
    }

    /**
     * Create an instance of {@link SubjectInformation }
     * 
     */
    public SubjectInformation createSubjectInformation() {
        return new SubjectInformation();
    }

    /**
     * Create an instance of {@link ComingIntoForce }
     * 
     */
    public ComingIntoForce createComingIntoForce() {
        return new ComingIntoForce();
    }

    /**
     * Create an instance of {@link P2Group }
     * 
     */
    public P2Group createP2Group() {
        return new P2Group();
    }

    /**
     * Create an instance of {@link InlineFullStructure }
     * 
     */
    public InlineFullStructure createInlineFullStructure() {
        return new InlineFullStructure();
    }

    /**
     * Create an instance of {@link P2 }
     * 
     */
    public P2 createP2() {
        return new P2();
    }

    /**
     * Create an instance of {@link Pnumber }
     * 
     */
    public Pnumber createPnumber() {
        return new Pnumber();
    }

    /**
     * Create an instance of {@link ChangeType }
     * 
     */
    public ChangeType createChangeType() {
        return new ChangeType();
    }

    /**
     * Create an instance of {@link Repeal }
     * 
     */
    public Repeal createRepeal() {
        return new Repeal();
    }

    /**
     * Create an instance of {@link CommentaryRef }
     * 
     */
    public CommentaryRef createCommentaryRef() {
        return new CommentaryRef();
    }

    /**
     * Create an instance of {@link Acronym }
     * 
     */
    public Acronym createAcronym() {
        return new Acronym();
    }

    /**
     * Create an instance of {@link Character }
     * 
     */
    public Character createCharacter() {
        return new Character();
    }

    /**
     * Create an instance of {@link uk.gov.legislation.namespaces.legislation.Strong }
     * 
     */
    public uk.gov.legislation.namespaces.legislation.Strong createStrong() {
        return new uk.gov.legislation.namespaces.legislation.Strong();
    }

    /**
     * Create an instance of {@link uk.gov.legislation.namespaces.legislation.Emphasis }
     * 
     */
    public uk.gov.legislation.namespaces.legislation.Emphasis createEmphasis() {
        return new uk.gov.legislation.namespaces.legislation.Emphasis();
    }

    /**
     * Create an instance of {@link InlineStructure }
     * 
     */
    public InlineStructure createInlineStructure() {
        return new InlineStructure();
    }

    /**
     * Create an instance of {@link uk.gov.legislation.namespaces.legislation.SmallCaps }
     * 
     */
    public uk.gov.legislation.namespaces.legislation.SmallCaps createSmallCaps() {
        return new uk.gov.legislation.namespaces.legislation.SmallCaps();
    }

    /**
     * Create an instance of {@link InlineAmendment }
     * 
     */
    public InlineAmendment createInlineAmendment() {
        return new InlineAmendment();
    }

    /**
     * Create an instance of {@link InlineExtract }
     * 
     */
    public InlineExtract createInlineExtract() {
        return new InlineExtract();
    }

    /**
     * Create an instance of {@link FootnoteRef }
     * 
     */
    public FootnoteRef createFootnoteRef() {
        return new FootnoteRef();
    }

    /**
     * Create an instance of {@link MarginNoteRef }
     * 
     */
    public MarginNoteRef createMarginNoteRef() {
        return new MarginNoteRef();
    }

    /**
     * Create an instance of {@link InternalLink }
     * 
     */
    public InternalLink createInternalLink() {
        return new InternalLink();
    }

    /**
     * Create an instance of {@link ExternalLink }
     * 
     */
    public ExternalLink createExternalLink() {
        return new ExternalLink();
    }

    /**
     * Create an instance of {@link Citation }
     * 
     */
    public Citation createCitation() {
        return new Citation();
    }

    /**
     * Create an instance of {@link Abbreviation }
     * 
     */
    public Abbreviation createAbbreviation() {
        return new Abbreviation();
    }

    /**
     * Create an instance of {@link Term.Strong }
     * 
     */
    public Term.Strong createTermStrong() {
        return new Term.Strong();
    }

    /**
     * Create an instance of {@link Term.Emphasis }
     * 
     */
    public Term.Emphasis createTermEmphasis() {
        return new Term.Emphasis();
    }

    /**
     * Create an instance of {@link Term.Inferior }
     * 
     */
    public Term.Inferior createTermInferior() {
        return new Term.Inferior();
    }

    /**
     * Create an instance of {@link Term.Superior }
     * 
     */
    public Term.Superior createTermSuperior() {
        return new Term.Superior();
    }

    /**
     * Create an instance of {@link Term.SmallCaps }
     * 
     */
    public Term.SmallCaps createTermSmallCaps() {
        return new Term.SmallCaps();
    }

    /**
     * Create an instance of {@link Term.Underline }
     * 
     */
    public Term.Underline createTermUnderline() {
        return new Term.Underline();
    }

    /**
     * Create an instance of {@link CitationSubRef }
     * 
     */
    public CitationSubRef createCitationSubRef() {
        return new CitationSubRef();
    }

    /**
     * Create an instance of {@link Definition }
     * 
     */
    public Definition createDefinition() {
        return new Definition();
    }

    /**
     * Create an instance of {@link CitationListRef }
     * 
     */
    public CitationListRef createCitationListRef() {
        return new CitationListRef();
    }

    /**
     * Create an instance of {@link Proviso }
     * 
     */
    public Proviso createProviso() {
        return new Proviso();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link P2Para }
     * 
     */
    public P2Para createP2Para() {
        return new P2Para();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link BlockText }
     * 
     */
    public BlockText createBlockText() {
        return new BlockText();
    }

    /**
     * Create an instance of {@link Para }
     * 
     */
    public Para createPara() {
        return new Para();
    }

    /**
     * Create an instance of {@link OrderedList }
     * 
     */
    public OrderedList createOrderedList() {
        return new OrderedList();
    }

    /**
     * Create an instance of {@link ListItem }
     * 
     */
    public ListItem createListItem() {
        return new ListItem();
    }

    /**
     * Create an instance of {@link ParaBasicStructure }
     * 
     */
    public ParaBasicStructure createParaBasicStructure() {
        return new ParaBasicStructure();
    }

    /**
     * Create an instance of {@link UnorderedList }
     * 
     */
    public UnorderedList createUnorderedList() {
        return new UnorderedList();
    }

    /**
     * Create an instance of {@link DecoratedGroup }
     * 
     */
    public DecoratedGroup createDecoratedGroup() {
        return new DecoratedGroup();
    }

    /**
     * Create an instance of {@link GroupItem }
     * 
     */
    public GroupItem createGroupItem() {
        return new GroupItem();
    }

    /**
     * Create an instance of {@link KeyList }
     * 
     */
    public KeyList createKeyList() {
        return new KeyList();
    }

    /**
     * Create an instance of {@link KeyListItem }
     * 
     */
    public KeyListItem createKeyListItem() {
        return new KeyListItem();
    }

    /**
     * Create an instance of {@link Figure }
     * 
     */
    public Figure createFigure() {
        return new Figure();
    }

    /**
     * Create an instance of {@link Notes }
     * 
     */
    public Notes createNotes() {
        return new Notes();
    }

    /**
     * Create an instance of {@link Footnote }
     * 
     */
    public Footnote createFootnote() {
        return new Footnote();
    }

    /**
     * Create an instance of {@link BasicStringStructure }
     * 
     */
    public BasicStringStructure createBasicStringStructure() {
        return new BasicStringStructure();
    }

    /**
     * Create an instance of {@link Form }
     * 
     */
    public Form createForm() {
        return new Form();
    }

    /**
     * Create an instance of {@link TitleBlock }
     * 
     */
    public TitleBlock createTitleBlock() {
        return new TitleBlock();
    }

    /**
     * Create an instance of {@link IncludedDocument }
     * 
     */
    public IncludedDocument createIncludedDocument() {
        return new IncludedDocument();
    }

    /**
     * Create an instance of {@link Part }
     * 
     */
    public Part createPart() {
        return new Part();
    }

    /**
     * Create an instance of {@link P }
     * 
     */
    public P createP() {
        return new P();
    }

    /**
     * Create an instance of {@link Tabular.TableText }
     * 
     */
    public Tabular.TableText createTabularTableText() {
        return new Tabular.TableText();
    }

    /**
     * Create an instance of {@link Formula }
     * 
     */
    public Formula createFormula() {
        return new Formula();
    }

    /**
     * Create an instance of {@link Where }
     * 
     */
    public Where createWhere() {
        return new Where();
    }

    /**
     * Create an instance of {@link P1 }
     * 
     */
    public P1 createP1() {
        return new P1();
    }

    /**
     * Create an instance of {@link P1Para }
     * 
     */
    public P1Para createP1Para() {
        return new P1Para();
    }

    /**
     * Create an instance of {@link BlockAmendment }
     * 
     */
    public BlockAmendment createBlockAmendment() {
        return new BlockAmendment();
    }

    /**
     * Create an instance of {@link PrimaryPreamble }
     * 
     */
    public PrimaryPreamble createPrimaryPreamble() {
        return new PrimaryPreamble();
    }

    /**
     * Create an instance of {@link IntroductoryText }
     * 
     */
    public IntroductoryText createIntroductoryText() {
        return new IntroductoryText();
    }

    /**
     * Create an instance of {@link EnactingTextOmitted }
     * 
     */
    public EnactingTextOmitted createEnactingTextOmitted() {
        return new EnactingTextOmitted();
    }

    /**
     * Create an instance of {@link EnactingText }
     * 
     */
    public EnactingText createEnactingText() {
        return new EnactingText();
    }

    /**
     * Create an instance of {@link SecondaryPreamble }
     * 
     */
    public SecondaryPreamble createSecondaryPreamble() {
        return new SecondaryPreamble();
    }

    /**
     * Create an instance of {@link Resolution }
     * 
     */
    public Resolution createResolution() {
        return new Resolution();
    }

    /**
     * Create an instance of {@link RoyalPresence }
     * 
     */
    public RoyalPresence createRoyalPresence() {
        return new RoyalPresence();
    }

    /**
     * Create an instance of {@link Body }
     * 
     */
    public Body createBody() {
        return new Body();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link P1Group }
     * 
     */
    public P1Group createP1Group() {
        return new P1Group();
    }

    /**
     * Create an instance of {@link Include }
     * 
     */
    public Include createInclude() {
        return new Include();
    }

    /**
     * Create an instance of {@link Chapter }
     * 
     */
    public Chapter createChapter() {
        return new Chapter();
    }

    /**
     * Create an instance of {@link Pblock }
     * 
     */
    public Pblock createPblock() {
        return new Pblock();
    }

    /**
     * Create an instance of {@link PsubBlock }
     * 
     */
    public PsubBlock createPsubBlock() {
        return new PsubBlock();
    }

    /**
     * Create an instance of {@link SignedSection }
     * 
     */
    public SignedSection createSignedSection() {
        return new SignedSection();
    }

    /**
     * Create an instance of {@link Signatory }
     * 
     */
    public Signatory createSignatory() {
        return new Signatory();
    }

    /**
     * Create an instance of {@link Signee }
     * 
     */
    public Signee createSignee() {
        return new Signee();
    }

    /**
     * Create an instance of {@link LSseal }
     * 
     */
    public LSseal createLSseal() {
        return new LSseal();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link DateSigned }
     * 
     */
    public DateSigned createDateSigned() {
        return new DateSigned();
    }

    /**
     * Create an instance of {@link InlineRestrictedStructure }
     * 
     */
    public InlineRestrictedStructure createInlineRestrictedStructure() {
        return new InlineRestrictedStructure();
    }

    /**
     * Create an instance of {@link Appendix }
     * 
     */
    public Appendix createAppendix() {
        return new Appendix();
    }

    /**
     * Create an instance of {@link Contents }
     * 
     */
    public Contents createContents() {
        return new Contents();
    }

    /**
     * Create an instance of {@link ContentsTitle }
     * 
     */
    public ContentsTitle createContentsTitle() {
        return new ContentsTitle();
    }

    /**
     * Create an instance of {@link ContentsGroup }
     * 
     */
    public ContentsGroup createContentsGroup() {
        return new ContentsGroup();
    }

    /**
     * Create an instance of {@link ContentsPart }
     * 
     */
    public ContentsPart createContentsPart() {
        return new ContentsPart();
    }

    /**
     * Create an instance of {@link ContentsChapter }
     * 
     */
    public ContentsChapter createContentsChapter() {
        return new ContentsChapter();
    }

    /**
     * Create an instance of {@link ContentsPblock }
     * 
     */
    public ContentsPblock createContentsPblock() {
        return new ContentsPblock();
    }

    /**
     * Create an instance of {@link ContentsPsubBlock }
     * 
     */
    public ContentsPsubBlock createContentsPsubBlock() {
        return new ContentsPsubBlock();
    }

    /**
     * Create an instance of {@link ContentsItem }
     * 
     */
    public ContentsItem createContentsItem() {
        return new ContentsItem();
    }

    /**
     * Create an instance of {@link ContentsSubItem }
     * 
     */
    public ContentsSubItem createContentsSubItem() {
        return new ContentsSubItem();
    }

    /**
     * Create an instance of {@link ContentsAppendix }
     * 
     */
    public ContentsAppendix createContentsAppendix() {
        return new ContentsAppendix();
    }

    /**
     * Create an instance of {@link ContentsSchedules }
     * 
     */
    public ContentsSchedules createContentsSchedules() {
        return new ContentsSchedules();
    }

    /**
     * Create an instance of {@link ContentsSchedule }
     * 
     */
    public ContentsSchedule createContentsSchedule() {
        return new ContentsSchedule();
    }

    /**
     * Create an instance of {@link AppendixBody }
     * 
     */
    public AppendixBody createAppendixBody() {
        return new AppendixBody();
    }

    /**
     * Create an instance of {@link P3 }
     * 
     */
    public P3 createP3() {
        return new P3();
    }

    /**
     * Create an instance of {@link P3Para }
     * 
     */
    public P3Para createP3Para() {
        return new P3Para();
    }

    /**
     * Create an instance of {@link AppendText }
     * 
     */
    public AppendText createAppendText() {
        return new AppendText();
    }

    /**
     * Create an instance of {@link BlockExtract }
     * 
     */
    public BlockExtract createBlockExtract() {
        return new BlockExtract();
    }

    /**
     * Create an instance of {@link P4 }
     * 
     */
    public P4 createP4() {
        return new P4();
    }

    /**
     * Create an instance of {@link P4Para }
     * 
     */
    public P4Para createP4Para() {
        return new P4Para();
    }

    /**
     * Create an instance of {@link P5 }
     * 
     */
    public P5 createP5() {
        return new P5();
    }

    /**
     * Create an instance of {@link P5Para }
     * 
     */
    public P5Para createP5Para() {
        return new P5Para();
    }

    /**
     * Create an instance of {@link P6 }
     * 
     */
    public P6 createP6() {
        return new P6();
    }

    /**
     * Create an instance of {@link P6Para }
     * 
     */
    public P6Para createP6Para() {
        return new P6Para();
    }

    /**
     * Create an instance of {@link P7 }
     * 
     */
    public P7 createP7() {
        return new P7();
    }

    /**
     * Create an instance of {@link P7Para }
     * 
     */
    public P7Para createP7Para() {
        return new P7Para();
    }

    /**
     * Create an instance of {@link P3Group }
     * 
     */
    public P3Group createP3Group() {
        return new P3Group();
    }

    /**
     * Create an instance of {@link Schedules }
     * 
     */
    public Schedules createSchedules() {
        return new Schedules();
    }

    /**
     * Create an instance of {@link Abstract }
     * 
     */
    public Abstract createAbstract() {
        return new Abstract();
    }

    /**
     * Create an instance of {@link AbstractBody }
     * 
     */
    public AbstractBody createAbstractBody() {
        return new AbstractBody();
    }

    /**
     * Create an instance of {@link Schedule }
     * 
     */
    public Schedule createSchedule() {
        return new Schedule();
    }

    /**
     * Create an instance of {@link ScheduleBody }
     * 
     */
    public ScheduleBody createScheduleBody() {
        return new ScheduleBody();
    }

    /**
     * Create an instance of {@link FragmentNumber }
     * 
     */
    public FragmentNumber createFragmentNumber() {
        return new FragmentNumber();
    }

    /**
     * Create an instance of {@link FragmentTitle }
     * 
     */
    public FragmentTitle createFragmentTitle() {
        return new FragmentTitle();
    }

    /**
     * Create an instance of {@link GroupItemRef }
     * 
     */
    public GroupItemRef createGroupItemRef() {
        return new GroupItemRef();
    }

    /**
     * Create an instance of {@link BinaryContent }
     * 
     */
    public BinaryContent createBinaryContent() {
        return new BinaryContent();
    }

    /**
     * Create an instance of {@link PrimaryPrelims }
     * 
     */
    public PrimaryPrelims createPrimaryPrelims() {
        return new PrimaryPrelims();
    }

    /**
     * Create an instance of {@link DateOfEnactment }
     * 
     */
    public DateOfEnactment createDateOfEnactment() {
        return new DateOfEnactment();
    }

    /**
     * Create an instance of {@link Commentary }
     * 
     */
    public Commentary createCommentary() {
        return new Commentary();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link CitationList }
     * 
     */
    public CitationList createCitationList() {
        return new CitationList();
    }

    /**
     * Create an instance of {@link Legislation }
     * 
     */
    public Legislation createLegislation() {
        return new Legislation();
    }

    /**
     * Create an instance of {@link Secondary }
     * 
     */
    public Secondary createSecondary() {
        return new Secondary();
    }

    /**
     * Create an instance of {@link SecondaryPrelims }
     * 
     */
    public SecondaryPrelims createSecondaryPrelims() {
        return new SecondaryPrelims();
    }

    /**
     * Create an instance of {@link SubjectInformation.Subject }
     * 
     */
    public SubjectInformation.Subject createSubjectInformationSubject() {
        return new SubjectInformation.Subject();
    }

    /**
     * Create an instance of {@link LaidDraft }
     * 
     */
    public LaidDraft createLaidDraft() {
        return new LaidDraft();
    }

    /**
     * Create an instance of {@link MadeDate }
     * 
     */
    public MadeDate createMadeDate() {
        return new MadeDate();
    }

    /**
     * Create an instance of {@link LaidDate }
     * 
     */
    public LaidDate createLaidDate() {
        return new LaidDate();
    }

    /**
     * Create an instance of {@link ComingIntoForce.ComingIntoForceClauses }
     * 
     */
    public ComingIntoForce.ComingIntoForceClauses createComingIntoForceComingIntoForceClauses() {
        return new ComingIntoForce.ComingIntoForceClauses();
    }

    /**
     * Create an instance of {@link ExplanatoryNotes }
     * 
     */
    public ExplanatoryNotes createExplanatoryNotes() {
        return new ExplanatoryNotes();
    }

    /**
     * Create an instance of {@link EarlierOrders }
     * 
     */
    public EarlierOrders createEarlierOrders() {
        return new EarlierOrders();
    }

    /**
     * Create an instance of {@link Primary }
     * 
     */
    public Primary createPrimary() {
        return new Primary();
    }

    /**
     * Create an instance of {@link Footnotes }
     * 
     */
    public Footnotes createFootnotes() {
        return new Footnotes();
    }

    /**
     * Create an instance of {@link MarginNotes }
     * 
     */
    public MarginNotes createMarginNotes() {
        return new MarginNotes();
    }

    /**
     * Create an instance of {@link MarginNote }
     * 
     */
    public MarginNote createMarginNote() {
        return new MarginNote();
    }

    /**
     * Create an instance of {@link Versions }
     * 
     */
    public Versions createVersions() {
        return new Versions();
    }

    /**
     * Create an instance of {@link Version }
     * 
     */
    public Version createVersion() {
        return new Version();
    }

    /**
     * Create an instance of {@link Resources }
     * 
     */
    public Resources createResources() {
        return new Resources();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link InternalVersion }
     * 
     */
    public InternalVersion createInternalVersion() {
        return new InternalVersion();
    }

    /**
     * Create an instance of {@link XMLcontent }
     * 
     */
    public XMLcontent createXMLcontent() {
        return new XMLcontent();
    }

    /**
     * Create an instance of {@link ExternalVersion }
     * 
     */
    public ExternalVersion createExternalVersion() {
        return new ExternalVersion();
    }

    /**
     * Create an instance of {@link ResourceGroup }
     * 
     */
    public ResourceGroup createResourceGroup() {
        return new ResourceGroup();
    }

    /**
     * Create an instance of {@link Commentaries }
     * 
     */
    public Commentaries createCommentaries() {
        return new Commentaries();
    }

    /**
     * Create an instance of {@link CitationLists }
     * 
     */
    public CitationLists createCitationLists() {
        return new CitationLists();
    }

    /**
     * Create an instance of {@link ENprelims }
     * 
     */
    public ENprelims createENprelims() {
        return new ENprelims();
    }

    /**
     * Create an instance of {@link BlockSectionStructure }
     * 
     */
    public BlockSectionStructure createBlockSectionStructure() {
        return new BlockSectionStructure();
    }

    /**
     * Create an instance of {@link BlockBasicStructure }
     * 
     */
    public BlockBasicStructure createBlockBasicStructure() {
        return new BlockBasicStructure();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Superior }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Superior", scope = Term.Underline.class)
    public JAXBElement<Term.Superior> createTermUnderlineSuperior(Term.Superior value) {
        return new JAXBElement<Term.Superior>(_TermUnderlineSuperior_QNAME, Term.Superior.class, Term.Underline.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Inferior }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Inferior", scope = Term.Underline.class)
    public JAXBElement<Term.Inferior> createTermUnderlineInferior(Term.Inferior value) {
        return new JAXBElement<Term.Inferior>(_TermUnderlineInferior_QNAME, Term.Inferior.class, Term.Underline.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.SmallCaps }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "SmallCaps", scope = Term.Underline.class)
    public JAXBElement<Term.SmallCaps> createTermUnderlineSmallCaps(Term.SmallCaps value) {
        return new JAXBElement<Term.SmallCaps>(_TermUnderlineSmallCaps_QNAME, Term.SmallCaps.class, Term.Underline.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Emphasis }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Emphasis", scope = Term.Underline.class)
    public JAXBElement<Term.Emphasis> createTermUnderlineEmphasis(Term.Emphasis value) {
        return new JAXBElement<Term.Emphasis>(_TermUnderlineEmphasis_QNAME, Term.Emphasis.class, Term.Underline.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Strong }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Strong", scope = Term.Underline.class)
    public JAXBElement<Term.Strong> createTermUnderlineStrong(Term.Strong value) {
        return new JAXBElement<Term.Strong>(_TermUnderlineStrong_QNAME, Term.Strong.class, Term.Underline.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InlineRestrictedStructure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "ContentsNumber")
    public JAXBElement<InlineRestrictedStructure> createContentsNumber(InlineRestrictedStructure value) {
        return new JAXBElement<InlineRestrictedStructure>(_ContentsNumber_QNAME, InlineRestrictedStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InlineFullStructure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Title")
    public JAXBElement<InlineFullStructure> createTitle(InlineFullStructure value) {
        return new JAXBElement<InlineFullStructure>(_Title_QNAME, InlineFullStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InlineStructure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Inferior")
    public JAXBElement<InlineStructure> createInferior(InlineStructure value) {
        return new JAXBElement<InlineStructure>(_TermUnderlineInferior_QNAME, InlineStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InlineStructure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Span")
    public JAXBElement<InlineStructure> createSpan(InlineStructure value) {
        return new JAXBElement<InlineStructure>(_Span_QNAME, InlineStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InlineStructure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Underline")
    public JAXBElement<InlineStructure> createUnderline(InlineStructure value) {
        return new JAXBElement<InlineStructure>(_Underline_QNAME, InlineStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InlineFullStructure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Key")
    public JAXBElement<InlineFullStructure> createKey(InlineFullStructure value) {
        return new JAXBElement<InlineFullStructure>(_Key_QNAME, InlineFullStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InlineStructure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "PersonName")
    public JAXBElement<InlineStructure> createPersonName(InlineStructure value) {
        return new JAXBElement<InlineStructure>(_PersonName_QNAME, InlineStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InlineFullStructure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Subtitle")
    public JAXBElement<InlineFullStructure> createSubtitle(InlineFullStructure value) {
        return new JAXBElement<InlineFullStructure>(_Subtitle_QNAME, InlineFullStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InlineStructure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "JobTitle")
    public JAXBElement<InlineStructure> createJobTitle(InlineStructure value) {
        return new JAXBElement<InlineStructure>(_JobTitle_QNAME, InlineStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InlineRestrictedStructure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Approved")
    public JAXBElement<InlineRestrictedStructure> createApproved(InlineRestrictedStructure value) {
        return new JAXBElement<InlineRestrictedStructure>(_Approved_QNAME, InlineRestrictedStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InlineRestrictedStructure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "DateText")
    public JAXBElement<InlineRestrictedStructure> createDateText(InlineRestrictedStructure value) {
        return new JAXBElement<InlineRestrictedStructure>(_DateText_QNAME, InlineRestrictedStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InlineStructure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Superior")
    public JAXBElement<InlineStructure> createSuperior(InlineStructure value) {
        return new JAXBElement<InlineStructure>(_TermUnderlineSuperior_QNAME, InlineStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChangeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Addition")
    public JAXBElement<ChangeType> createAddition(ChangeType value) {
        return new JAXBElement<ChangeType>(_Addition_QNAME, ChangeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InlineStructure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Department")
    public JAXBElement<InlineStructure> createDepartment(InlineStructure value) {
        return new JAXBElement<InlineStructure>(_Department_QNAME, InlineStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParaBasicStructure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Correction")
    public JAXBElement<ParaBasicStructure> createCorrection(ParaBasicStructure value) {
        return new JAXBElement<ParaBasicStructure>(_Correction_QNAME, ParaBasicStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InlineFullStructure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Number")
    public JAXBElement<InlineFullStructure> createNumber(InlineFullStructure value) {
        return new JAXBElement<InlineFullStructure>(_Number_QNAME, InlineFullStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InlineFullStructure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Reference")
    public JAXBElement<InlineFullStructure> createReference(InlineFullStructure value) {
        return new JAXBElement<InlineFullStructure>(_Reference_QNAME, InlineFullStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChangeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Substitution")
    public JAXBElement<ChangeType> createSubstitution(ChangeType value) {
        return new JAXBElement<ChangeType>(_Substitution_QNAME, ChangeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParaBasicStructure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Draft")
    public JAXBElement<ParaBasicStructure> createDraft(ParaBasicStructure value) {
        return new JAXBElement<ParaBasicStructure>(_Draft_QNAME, ParaBasicStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InlineStructure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "LongTitle")
    public JAXBElement<InlineStructure> createLongTitle(InlineStructure value) {
        return new JAXBElement<InlineStructure>(_LongTitle_QNAME, InlineStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Superior }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Superior", scope = Term.class)
    public JAXBElement<Term.Superior> createTermSuperior(Term.Superior value) {
        return new JAXBElement<Term.Superior>(_TermUnderlineSuperior_QNAME, Term.Superior.class, Term.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Inferior }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Inferior", scope = Term.class)
    public JAXBElement<Term.Inferior> createTermInferior(Term.Inferior value) {
        return new JAXBElement<Term.Inferior>(_TermUnderlineInferior_QNAME, Term.Inferior.class, Term.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.SmallCaps }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "SmallCaps", scope = Term.class)
    public JAXBElement<Term.SmallCaps> createTermSmallCaps(Term.SmallCaps value) {
        return new JAXBElement<Term.SmallCaps>(_TermUnderlineSmallCaps_QNAME, Term.SmallCaps.class, Term.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Emphasis }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Emphasis", scope = Term.class)
    public JAXBElement<Term.Emphasis> createTermEmphasis(Term.Emphasis value) {
        return new JAXBElement<Term.Emphasis>(_TermUnderlineEmphasis_QNAME, Term.Emphasis.class, Term.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Underline }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Underline", scope = Term.class)
    public JAXBElement<Term.Underline> createTermUnderline(Term.Underline value) {
        return new JAXBElement<Term.Underline>(_Underline_QNAME, Term.Underline.class, Term.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Strong }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Strong", scope = Term.class)
    public JAXBElement<Term.Strong> createTermStrong(Term.Strong value) {
        return new JAXBElement<Term.Strong>(_TermUnderlineStrong_QNAME, Term.Strong.class, Term.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubjectInformation.Subject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Subject", scope = SubjectInformation.class)
    public JAXBElement<SubjectInformation.Subject> createSubjectInformationSubject(SubjectInformation.Subject value) {
        return new JAXBElement<SubjectInformation.Subject>(_SubjectInformationSubject_QNAME, SubjectInformation.Subject.class, SubjectInformation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Superior }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Superior", scope = Term.Emphasis.class)
    public JAXBElement<Term.Superior> createTermEmphasisSuperior(Term.Superior value) {
        return new JAXBElement<Term.Superior>(_TermUnderlineSuperior_QNAME, Term.Superior.class, Term.Emphasis.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Inferior }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Inferior", scope = Term.Emphasis.class)
    public JAXBElement<Term.Inferior> createTermEmphasisInferior(Term.Inferior value) {
        return new JAXBElement<Term.Inferior>(_TermUnderlineInferior_QNAME, Term.Inferior.class, Term.Emphasis.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.SmallCaps }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "SmallCaps", scope = Term.Emphasis.class)
    public JAXBElement<Term.SmallCaps> createTermEmphasisSmallCaps(Term.SmallCaps value) {
        return new JAXBElement<Term.SmallCaps>(_TermUnderlineSmallCaps_QNAME, Term.SmallCaps.class, Term.Emphasis.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Underline }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Underline", scope = Term.Emphasis.class)
    public JAXBElement<Term.Underline> createTermEmphasisUnderline(Term.Underline value) {
        return new JAXBElement<Term.Underline>(_Underline_QNAME, Term.Underline.class, Term.Emphasis.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Strong }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Strong", scope = Term.Emphasis.class)
    public JAXBElement<Term.Strong> createTermEmphasisStrong(Term.Strong value) {
        return new JAXBElement<Term.Strong>(_TermUnderlineStrong_QNAME, Term.Strong.class, Term.Emphasis.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Superior }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Superior", scope = Term.Superior.class)
    public JAXBElement<Term.Superior> createTermSuperiorSuperior(Term.Superior value) {
        return new JAXBElement<Term.Superior>(_TermUnderlineSuperior_QNAME, Term.Superior.class, Term.Superior.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Inferior }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Inferior", scope = Term.Superior.class)
    public JAXBElement<Term.Inferior> createTermSuperiorInferior(Term.Inferior value) {
        return new JAXBElement<Term.Inferior>(_TermUnderlineInferior_QNAME, Term.Inferior.class, Term.Superior.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.SmallCaps }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "SmallCaps", scope = Term.Superior.class)
    public JAXBElement<Term.SmallCaps> createTermSuperiorSmallCaps(Term.SmallCaps value) {
        return new JAXBElement<Term.SmallCaps>(_TermUnderlineSmallCaps_QNAME, Term.SmallCaps.class, Term.Superior.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Emphasis }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Emphasis", scope = Term.Superior.class)
    public JAXBElement<Term.Emphasis> createTermSuperiorEmphasis(Term.Emphasis value) {
        return new JAXBElement<Term.Emphasis>(_TermUnderlineEmphasis_QNAME, Term.Emphasis.class, Term.Superior.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Strong }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Strong", scope = Term.Superior.class)
    public JAXBElement<Term.Strong> createTermSuperiorStrong(Term.Strong value) {
        return new JAXBElement<Term.Strong>(_TermUnderlineStrong_QNAME, Term.Strong.class, Term.Superior.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Superior }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Superior", scope = Term.SmallCaps.class)
    public JAXBElement<Term.Superior> createTermSmallCapsSuperior(Term.Superior value) {
        return new JAXBElement<Term.Superior>(_TermUnderlineSuperior_QNAME, Term.Superior.class, Term.SmallCaps.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Inferior }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Inferior", scope = Term.SmallCaps.class)
    public JAXBElement<Term.Inferior> createTermSmallCapsInferior(Term.Inferior value) {
        return new JAXBElement<Term.Inferior>(_TermUnderlineInferior_QNAME, Term.Inferior.class, Term.SmallCaps.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Emphasis }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Emphasis", scope = Term.SmallCaps.class)
    public JAXBElement<Term.Emphasis> createTermSmallCapsEmphasis(Term.Emphasis value) {
        return new JAXBElement<Term.Emphasis>(_TermUnderlineEmphasis_QNAME, Term.Emphasis.class, Term.SmallCaps.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Underline }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Underline", scope = Term.SmallCaps.class)
    public JAXBElement<Term.Underline> createTermSmallCapsUnderline(Term.Underline value) {
        return new JAXBElement<Term.Underline>(_Underline_QNAME, Term.Underline.class, Term.SmallCaps.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Strong }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Strong", scope = Term.SmallCaps.class)
    public JAXBElement<Term.Strong> createTermSmallCapsStrong(Term.Strong value) {
        return new JAXBElement<Term.Strong>(_TermUnderlineStrong_QNAME, Term.Strong.class, Term.SmallCaps.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Superior }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Superior", scope = Term.Strong.class)
    public JAXBElement<Term.Superior> createTermStrongSuperior(Term.Superior value) {
        return new JAXBElement<Term.Superior>(_TermUnderlineSuperior_QNAME, Term.Superior.class, Term.Strong.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Inferior }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Inferior", scope = Term.Strong.class)
    public JAXBElement<Term.Inferior> createTermStrongInferior(Term.Inferior value) {
        return new JAXBElement<Term.Inferior>(_TermUnderlineInferior_QNAME, Term.Inferior.class, Term.Strong.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.SmallCaps }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "SmallCaps", scope = Term.Strong.class)
    public JAXBElement<Term.SmallCaps> createTermStrongSmallCaps(Term.SmallCaps value) {
        return new JAXBElement<Term.SmallCaps>(_TermUnderlineSmallCaps_QNAME, Term.SmallCaps.class, Term.Strong.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Emphasis }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Emphasis", scope = Term.Strong.class)
    public JAXBElement<Term.Emphasis> createTermStrongEmphasis(Term.Emphasis value) {
        return new JAXBElement<Term.Emphasis>(_TermUnderlineEmphasis_QNAME, Term.Emphasis.class, Term.Strong.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Underline }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Underline", scope = Term.Strong.class)
    public JAXBElement<Term.Underline> createTermStrongUnderline(Term.Underline value) {
        return new JAXBElement<Term.Underline>(_Underline_QNAME, Term.Underline.class, Term.Strong.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Superior }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Superior", scope = Term.Inferior.class)
    public JAXBElement<Term.Superior> createTermInferiorSuperior(Term.Superior value) {
        return new JAXBElement<Term.Superior>(_TermUnderlineSuperior_QNAME, Term.Superior.class, Term.Inferior.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Inferior }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Inferior", scope = Term.Inferior.class)
    public JAXBElement<Term.Inferior> createTermInferiorInferior(Term.Inferior value) {
        return new JAXBElement<Term.Inferior>(_TermUnderlineInferior_QNAME, Term.Inferior.class, Term.Inferior.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.SmallCaps }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "SmallCaps", scope = Term.Inferior.class)
    public JAXBElement<Term.SmallCaps> createTermInferiorSmallCaps(Term.SmallCaps value) {
        return new JAXBElement<Term.SmallCaps>(_TermUnderlineSmallCaps_QNAME, Term.SmallCaps.class, Term.Inferior.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Emphasis }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Emphasis", scope = Term.Inferior.class)
    public JAXBElement<Term.Emphasis> createTermInferiorEmphasis(Term.Emphasis value) {
        return new JAXBElement<Term.Emphasis>(_TermUnderlineEmphasis_QNAME, Term.Emphasis.class, Term.Inferior.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Strong }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Strong", scope = Term.Inferior.class)
    public JAXBElement<Term.Strong> createTermInferiorStrong(Term.Strong value) {
        return new JAXBElement<Term.Strong>(_TermUnderlineStrong_QNAME, Term.Strong.class, Term.Inferior.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Superior }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Superior", scope = InlineRestrictedStructure.class)
    public JAXBElement<Term.Superior> createInlineRestrictedStructureSuperior(Term.Superior value) {
        return new JAXBElement<Term.Superior>(_TermUnderlineSuperior_QNAME, Term.Superior.class, InlineRestrictedStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Inferior }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Inferior", scope = InlineRestrictedStructure.class)
    public JAXBElement<Term.Inferior> createInlineRestrictedStructureInferior(Term.Inferior value) {
        return new JAXBElement<Term.Inferior>(_TermUnderlineInferior_QNAME, Term.Inferior.class, InlineRestrictedStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.SmallCaps }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "SmallCaps", scope = InlineRestrictedStructure.class)
    public JAXBElement<Term.SmallCaps> createInlineRestrictedStructureSmallCaps(Term.SmallCaps value) {
        return new JAXBElement<Term.SmallCaps>(_TermUnderlineSmallCaps_QNAME, Term.SmallCaps.class, InlineRestrictedStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Emphasis }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Emphasis", scope = InlineRestrictedStructure.class)
    public JAXBElement<Term.Emphasis> createInlineRestrictedStructureEmphasis(Term.Emphasis value) {
        return new JAXBElement<Term.Emphasis>(_TermUnderlineEmphasis_QNAME, Term.Emphasis.class, InlineRestrictedStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Underline }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Underline", scope = InlineRestrictedStructure.class)
    public JAXBElement<Term.Underline> createInlineRestrictedStructureUnderline(Term.Underline value) {
        return new JAXBElement<Term.Underline>(_Underline_QNAME, Term.Underline.class, InlineRestrictedStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Term.Strong }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.legislation.gov.uk/namespaces/legislation", name = "Strong", scope = InlineRestrictedStructure.class)
    public JAXBElement<Term.Strong> createInlineRestrictedStructureStrong(Term.Strong value) {
        return new JAXBElement<Term.Strong>(_TermUnderlineStrong_QNAME, Term.Strong.class, InlineRestrictedStructure.class, value);
    }

}
