//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.07 at 06:17:52 PM CEST 
//


package uk.gov.legislation.namespaces.metadata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}DocumentClassification"/>
 *         &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}Year"/>
 *         &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}Number"/>
 *         &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}ISBN" minOccurs="0"/>
 *         &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}AlternativeNumber" minOccurs="0"/>
 *         &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}EnactmentDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}ComingIntoForce" minOccurs="0"/>
 *         &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}UnappliedEffects" minOccurs="0"/>
 *         &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}Citations" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "PrimaryMetadata")
public class PrimaryMetadata {

    @XmlElement(name = "DocumentClassification", required = true)
    protected DocumentClassification documentClassification;
    @XmlElement(name = "Year", required = true)
    protected Year year;
    @XmlElement(name = "Number", required = true)
    protected Number number;
    @XmlElement(name = "ISBN")
    protected ISBN isbn;
    @XmlElement(name = "AlternativeNumber")
    protected AlternativeNumber alternativeNumber;
    @XmlElement(name = "EnactmentDate")
    protected EnactmentDate enactmentDate;
    @XmlElement(name = "ComingIntoForce")
    protected ComingIntoForce comingIntoForce;
    @XmlElement(name = "UnappliedEffects")
    protected UnappliedEffects unappliedEffects;
    @XmlElement(name = "Citations")
    protected Citations citations;

    /**
     * Gets the value of the documentClassification property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentClassification }
     *     
     */
    public DocumentClassification getDocumentClassification() {
        return documentClassification;
    }

    /**
     * Sets the value of the documentClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentClassification }
     *     
     */
    public void setDocumentClassification(DocumentClassification value) {
        this.documentClassification = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link Year }
     *     
     */
    public Year getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link Year }
     *     
     */
    public void setYear(Year value) {
        this.year = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link Number }
     *     
     */
    public Number getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link Number }
     *     
     */
    public void setNumber(Number value) {
        this.number = value;
    }

    /**
     * Gets the value of the isbn property.
     * 
     * @return
     *     possible object is
     *     {@link ISBN }
     *     
     */
    public ISBN getISBN() {
        return isbn;
    }

    /**
     * Sets the value of the isbn property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISBN }
     *     
     */
    public void setISBN(ISBN value) {
        this.isbn = value;
    }

    /**
     * Gets the value of the alternativeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link AlternativeNumber }
     *     
     */
    public AlternativeNumber getAlternativeNumber() {
        return alternativeNumber;
    }

    /**
     * Sets the value of the alternativeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlternativeNumber }
     *     
     */
    public void setAlternativeNumber(AlternativeNumber value) {
        this.alternativeNumber = value;
    }

    /**
     * Gets the value of the enactmentDate property.
     * 
     * @return
     *     possible object is
     *     {@link EnactmentDate }
     *     
     */
    public EnactmentDate getEnactmentDate() {
        return enactmentDate;
    }

    /**
     * Sets the value of the enactmentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnactmentDate }
     *     
     */
    public void setEnactmentDate(EnactmentDate value) {
        this.enactmentDate = value;
    }

    /**
     * Gets the value of the comingIntoForce property.
     * 
     * @return
     *     possible object is
     *     {@link ComingIntoForce }
     *     
     */
    public ComingIntoForce getComingIntoForce() {
        return comingIntoForce;
    }

    /**
     * Sets the value of the comingIntoForce property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComingIntoForce }
     *     
     */
    public void setComingIntoForce(ComingIntoForce value) {
        this.comingIntoForce = value;
    }

    /**
     * Gets the value of the unappliedEffects property.
     * 
     * @return
     *     possible object is
     *     {@link UnappliedEffects }
     *     
     */
    public UnappliedEffects getUnappliedEffects() {
        return unappliedEffects;
    }

    /**
     * Sets the value of the unappliedEffects property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnappliedEffects }
     *     
     */
    public void setUnappliedEffects(UnappliedEffects value) {
        this.unappliedEffects = value;
    }

    /**
     * Gets the value of the citations property.
     * 
     * @return
     *     possible object is
     *     {@link Citations }
     *     
     */
    public Citations getCitations() {
        return citations;
    }

    /**
     * Sets the value of the citations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Citations }
     *     
     */
    public void setCitations(Citations value) {
        this.citations = value;
    }

}
