//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.07 at 06:17:52 PM CEST 
//


package uk.gov.legislation.namespaces.metadata;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}DocumentClassification"/&gt;
 *         &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}Year"/&gt;
 *         &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}Number" minOccurs="0"/&gt;
 *         &lt;choice maxOccurs="unbounded"&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}ISBN" minOccurs="0"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}AlternativeNumber" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}DepartmentCode" minOccurs="0"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}Made" minOccurs="0"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}Laid" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}ComingIntoForce" minOccurs="0"/&gt;
 *           &lt;choice&gt;
 *             &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}Resolution" minOccurs="0"/&gt;
 *             &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}RoyalPresence" minOccurs="0"/&gt;
 *           &lt;/choice&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}UnappliedEffects" minOccurs="0"/&gt;
 *           &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}Citations" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentClassification",
    "year",
    "number",
    "isbnsAndAlternativeNumbersAndDepartmentCodes"
})
@XmlRootElement(name = "SecondaryMetadata")
public class SecondaryMetadata {

    @XmlElement(name = "DocumentClassification", required = true)
    protected DocumentClassification documentClassification;
    @XmlElement(name = "Year", required = true)
    protected Year year;
    @XmlElement(name = "Number")
    protected Number number;
    @XmlElements({
        @XmlElement(name = "ISBN", type = ISBN.class),
        @XmlElement(name = "AlternativeNumber", type = AlternativeNumber.class),
        @XmlElement(name = "DepartmentCode", type = DepartmentCode.class),
        @XmlElement(name = "Made", type = Made.class),
        @XmlElement(name = "Laid", type = Laid.class),
        @XmlElement(name = "ComingIntoForce", type = ComingIntoForce.class),
        @XmlElement(name = "Resolution", type = Resolution.class),
        @XmlElement(name = "RoyalPresence", type = RoyalPresence.class),
        @XmlElement(name = "UnappliedEffects", type = UnappliedEffects.class),
        @XmlElement(name = "Citations", type = Citations.class)
    })
    protected List<Object> isbnsAndAlternativeNumbersAndDepartmentCodes;

    /**
     * Gets the value of the documentClassification property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentClassification }
     *     
     */
    public DocumentClassification getDocumentClassification() {
        return documentClassification;
    }

    /**
     * Sets the value of the documentClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentClassification }
     *     
     */
    public void setDocumentClassification(DocumentClassification value) {
        this.documentClassification = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link Year }
     *     
     */
    public Year getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link Year }
     *     
     */
    public void setYear(Year value) {
        this.year = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link Number }
     *     
     */
    public Number getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link Number }
     *     
     */
    public void setNumber(Number value) {
        this.number = value;
    }

    /**
     * Gets the value of the isbnsAndAlternativeNumbersAndDepartmentCodes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the isbnsAndAlternativeNumbersAndDepartmentCodes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getISBNSAndAlternativeNumbersAndDepartmentCodes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ISBN }
     * {@link AlternativeNumber }
     * {@link DepartmentCode }
     * {@link Made }
     * {@link Laid }
     * {@link ComingIntoForce }
     * {@link Resolution }
     * {@link RoyalPresence }
     * {@link UnappliedEffects }
     * {@link Citations }
     * 
     * 
     */
    public List<Object> getISBNSAndAlternativeNumbersAndDepartmentCodes() {
        if (isbnsAndAlternativeNumbersAndDepartmentCodes == null) {
            isbnsAndAlternativeNumbersAndDepartmentCodes = new ArrayList<>();
        }
        return this.isbnsAndAlternativeNumbersAndDepartmentCodes;
    }

}
