//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.07 at 06:17:52 PM CEST 
//


package uk.gov.legislation.namespaces.metadata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}TotalParagraphs" minOccurs="0"/>
 *         &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}BodyParagraphs" minOccurs="0"/>
 *         &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}ScheduleParagraphs" minOccurs="0"/>
 *         &lt;element ref="{http://www.legislation.gov.uk/namespaces/metadata}TotalImages" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "totalParagraphs",
    "bodyParagraphs",
    "scheduleParagraphs",
    "totalImages"
})
@XmlRootElement(name = "Statistics")
public class Statistics {

    @XmlElement(name = "TotalParagraphs")
    protected TotalParagraphs totalParagraphs;
    @XmlElement(name = "BodyParagraphs")
    protected BodyParagraphs bodyParagraphs;
    @XmlElement(name = "ScheduleParagraphs")
    protected ScheduleParagraphs scheduleParagraphs;
    @XmlElement(name = "TotalImages")
    protected TotalImages totalImages;

    /**
     * Gets the value of the totalParagraphs property.
     * 
     * @return
     *     possible object is
     *     {@link TotalParagraphs }
     *     
     */
    public TotalParagraphs getTotalParagraphs() {
        return totalParagraphs;
    }

    /**
     * Sets the value of the totalParagraphs property.
     * 
     * @param value
     *     allowed object is
     *     {@link TotalParagraphs }
     *     
     */
    public void setTotalParagraphs(TotalParagraphs value) {
        this.totalParagraphs = value;
    }

    /**
     * Gets the value of the bodyParagraphs property.
     * 
     * @return
     *     possible object is
     *     {@link BodyParagraphs }
     *     
     */
    public BodyParagraphs getBodyParagraphs() {
        return bodyParagraphs;
    }

    /**
     * Sets the value of the bodyParagraphs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodyParagraphs }
     *     
     */
    public void setBodyParagraphs(BodyParagraphs value) {
        this.bodyParagraphs = value;
    }

    /**
     * Gets the value of the scheduleParagraphs property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleParagraphs }
     *     
     */
    public ScheduleParagraphs getScheduleParagraphs() {
        return scheduleParagraphs;
    }

    /**
     * Sets the value of the scheduleParagraphs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleParagraphs }
     *     
     */
    public void setScheduleParagraphs(ScheduleParagraphs value) {
        this.scheduleParagraphs = value;
    }

    /**
     * Gets the value of the totalImages property.
     * 
     * @return
     *     possible object is
     *     {@link TotalImages }
     *     
     */
    public TotalImages getTotalImages() {
        return totalImages;
    }

    /**
     * Sets the value of the totalImages property.
     * 
     * @param value
     *     allowed object is
     *     {@link TotalImages }
     *     
     */
    public void setTotalImages(TotalImages value) {
        this.totalImages = value;
    }

}
