//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.07 at 06:17:52 PM CEST 
//


package uk.gov.legislation.namespaces.metadata;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AffectedProvisions" type="{http://www.legislation.gov.uk/namespaces/metadata}ProvisionsStructure" minOccurs="0"/&gt;
 *         &lt;element name="AffectingProvisions" type="{http://www.legislation.gov.uk/namespaces/metadata}ProvisionsStructure" minOccurs="0"/&gt;
 *         &lt;element name="Commenced" type="{http://www.legislation.gov.uk/namespaces/metadata}ProvisionsStructure" minOccurs="0"/&gt;
 *         &lt;element name="AffectedTitle" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="AffectingTitle" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Type" use="required" type="{http://www.w3.org/2001/XMLSchema}token" /&gt;
 *       &lt;attribute name="TypeNotes" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Notes" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Comments" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="AffectingURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *       &lt;attribute name="AffectingClass" type="{http://www.legislation.gov.uk/namespaces/metadata}DocumentMainTypeType" /&gt;
 *       &lt;attribute name="AffectingYear" type="{http://www.w3.org/2001/XMLSchema}gYear" /&gt;
 *       &lt;attribute name="AffectingNumber" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *       &lt;attribute name="AffectingProvisions" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="AffectedURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *       &lt;attribute name="AffectedClass" type="{http://www.legislation.gov.uk/namespaces/metadata}DocumentMainTypeType" /&gt;
 *       &lt;attribute name="AffectedYear" type="{http://www.w3.org/2001/XMLSchema}gYear" /&gt;
 *       &lt;attribute name="AffectedNumber" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *       &lt;attribute name="AffectedProvisions" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Index" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="Row" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="Modified" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *       &lt;attribute name="AppliedModified" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "affectedProvisionsList",
    "affectingProvisionsList",
    "commenced",
    "affectedTitles",
    "affectingTitles"
})
@XmlRootElement(name = "UnappliedEffect")
public class UnappliedEffect {

    @XmlElement(name = "AffectedProvisions")
    protected ProvisionsStructure affectedProvisionsList;
    @XmlElement(name = "AffectingProvisions")
    protected ProvisionsStructure affectingProvisionsList;
    @XmlElement(name = "Commenced")
    protected ProvisionsStructure commenced;
    @XmlElement(name = "AffectedTitle")
    protected List<String> affectedTitles;
    @XmlElement(name = "AffectingTitle")
    protected List<String> affectingTitles;
    @XmlAttribute(name = "Type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String type;
    @XmlAttribute(name = "TypeNotes")
    protected String typeNotes;
    @XmlAttribute(name = "Notes")
    protected String notes;
    @XmlAttribute(name = "Comments")
    protected String comments;
    @XmlAttribute(name = "AffectingURI")
    @XmlSchemaType(name = "anyURI")
    protected String affectingURI;
    @XmlAttribute(name = "AffectingClass")
    protected DocumentMainTypeType affectingClass;
    @XmlAttribute(name = "AffectingYear")
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar affectingYear;
    @XmlAttribute(name = "AffectingNumber")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger affectingNumber;
    @XmlAttribute(name = "AffectingProvisions")
    protected String affectingProvisions;
    @XmlAttribute(name = "AffectedURI")
    @XmlSchemaType(name = "anyURI")
    protected String affectedURI;
    @XmlAttribute(name = "AffectedClass")
    protected DocumentMainTypeType affectedClass;
    @XmlAttribute(name = "AffectedYear")
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar affectedYear;
    @XmlAttribute(name = "AffectedNumber")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger affectedNumber;
    @XmlAttribute(name = "AffectedProvisions")
    protected String affectedProvisions;
    @XmlAttribute(name = "Index")
    protected BigInteger index;
    @XmlAttribute(name = "Row")
    protected BigInteger row;
    @XmlAttribute(name = "Modified")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar modified;
    @XmlAttribute(name = "AppliedModified")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar appliedModified;

    /**
     * Gets the value of the affectedProvisionsList property.
     * 
     * @return
     *     possible object is
     *     {@link ProvisionsStructure }
     *     
     */
    public ProvisionsStructure getAffectedProvisionsList() {
        return affectedProvisionsList;
    }

    /**
     * Sets the value of the affectedProvisionsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProvisionsStructure }
     *     
     */
    public void setAffectedProvisionsList(ProvisionsStructure value) {
        this.affectedProvisionsList = value;
    }

    /**
     * Gets the value of the affectingProvisionsList property.
     * 
     * @return
     *     possible object is
     *     {@link ProvisionsStructure }
     *     
     */
    public ProvisionsStructure getAffectingProvisionsList() {
        return affectingProvisionsList;
    }

    /**
     * Sets the value of the affectingProvisionsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProvisionsStructure }
     *     
     */
    public void setAffectingProvisionsList(ProvisionsStructure value) {
        this.affectingProvisionsList = value;
    }

    /**
     * Gets the value of the commenced property.
     * 
     * @return
     *     possible object is
     *     {@link ProvisionsStructure }
     *     
     */
    public ProvisionsStructure getCommenced() {
        return commenced;
    }

    /**
     * Sets the value of the commenced property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProvisionsStructure }
     *     
     */
    public void setCommenced(ProvisionsStructure value) {
        this.commenced = value;
    }

    /**
     * Gets the value of the affectedTitles property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the affectedTitles property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAffectedTitles().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAffectedTitles() {
        if (affectedTitles == null) {
            affectedTitles = new ArrayList<>();
        }
        return this.affectedTitles;
    }

    /**
     * Gets the value of the affectingTitles property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the affectingTitles property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAffectingTitles().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAffectingTitles() {
        if (affectingTitles == null) {
            affectingTitles = new ArrayList<>();
        }
        return this.affectingTitles;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the typeNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeNotes() {
        return typeNotes;
    }

    /**
     * Sets the value of the typeNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeNotes(String value) {
        this.typeNotes = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the affectingURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffectingURI() {
        return affectingURI;
    }

    /**
     * Sets the value of the affectingURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffectingURI(String value) {
        this.affectingURI = value;
    }

    /**
     * Gets the value of the affectingClass property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentMainTypeType }
     *     
     */
    public DocumentMainTypeType getAffectingClass() {
        return affectingClass;
    }

    /**
     * Sets the value of the affectingClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentMainTypeType }
     *     
     */
    public void setAffectingClass(DocumentMainTypeType value) {
        this.affectingClass = value;
    }

    /**
     * Gets the value of the affectingYear property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAffectingYear() {
        return affectingYear;
    }

    /**
     * Sets the value of the affectingYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAffectingYear(XMLGregorianCalendar value) {
        this.affectingYear = value;
    }

    /**
     * Gets the value of the affectingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAffectingNumber() {
        return affectingNumber;
    }

    /**
     * Sets the value of the affectingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAffectingNumber(BigInteger value) {
        this.affectingNumber = value;
    }

    /**
     * Gets the value of the affectingProvisions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffectingProvisions() {
        return affectingProvisions;
    }

    /**
     * Sets the value of the affectingProvisions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffectingProvisions(String value) {
        this.affectingProvisions = value;
    }

    /**
     * Gets the value of the affectedURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffectedURI() {
        return affectedURI;
    }

    /**
     * Sets the value of the affectedURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffectedURI(String value) {
        this.affectedURI = value;
    }

    /**
     * Gets the value of the affectedClass property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentMainTypeType }
     *     
     */
    public DocumentMainTypeType getAffectedClass() {
        return affectedClass;
    }

    /**
     * Sets the value of the affectedClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentMainTypeType }
     *     
     */
    public void setAffectedClass(DocumentMainTypeType value) {
        this.affectedClass = value;
    }

    /**
     * Gets the value of the affectedYear property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAffectedYear() {
        return affectedYear;
    }

    /**
     * Sets the value of the affectedYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAffectedYear(XMLGregorianCalendar value) {
        this.affectedYear = value;
    }

    /**
     * Gets the value of the affectedNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAffectedNumber() {
        return affectedNumber;
    }

    /**
     * Sets the value of the affectedNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAffectedNumber(BigInteger value) {
        this.affectedNumber = value;
    }

    /**
     * Gets the value of the affectedProvisions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffectedProvisions() {
        return affectedProvisions;
    }

    /**
     * Sets the value of the affectedProvisions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffectedProvisions(String value) {
        this.affectedProvisions = value;
    }

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIndex(BigInteger value) {
        this.index = value;
    }

    /**
     * Gets the value of the row property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRow() {
        return row;
    }

    /**
     * Sets the value of the row property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRow(BigInteger value) {
        this.row = value;
    }

    /**
     * Gets the value of the modified property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getModified() {
        return modified;
    }

    /**
     * Sets the value of the modified property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setModified(XMLGregorianCalendar value) {
        this.modified = value;
    }

    /**
     * Gets the value of the appliedModified property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAppliedModified() {
        return appliedModified;
    }

    /**
     * Sets the value of the appliedModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAppliedModified(XMLGregorianCalendar value) {
        this.appliedModified = value;
    }

}
